### ISSUE TITLE
Order pod versions by SemVer

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods.org#119]
I'm grabbing the version but it needs to be ordered by SemVer. This [shows](https://github.com/CocoaPods/cocoapods.org/blob/pod_pages/app.rb#L68-L89) a working SQL query, but I'm not sure how to merge it with the Flounder stuff. 

Any ideas @floere ?

**Comment by segiddins** [comment]
just sort by `Pod::Version`?

**Comment by orta** [comment]
db is faster FWIW, but I am happy to do that if Florian recommends :+1:

**Comment by orta** [comment]
ping @floere

**Comment by floere** [comment]
Let's do it using `Pod::Version` for now and optimise later.

**Comment by segiddins** [comment]
@orta I'm up to do this right now, just point me to what needs sorting?

**Comment by orta** [comment]
Sure thing! 

https://github.com/CocoaPods/cocoapods.org/blob/pod_pages/app.rb#L68 without the `.first` is an SQL/Hashie array of all the versions, we need to loop the array searching for the highest SemVer version and have that as the "version" var

**Comment by orta** [comment]
can ditch the SQLat the same time

**Comment by floere** [comment]
... or use SQL if you'd like a challenge :)

**Comment by segiddins** [comment]
Done :)

**Comment by orta** [comment]
That's a lovely solution
