### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by pwightman** [CocoaPods/cocoapods.org#120]
[This page](http://guides.cocoapods.org/using/getting-started.html) has a broken link at the bottom that points to: http://guides.cocoapods.org/using/index.html which is empty.

![image](http://d.pr/i/1eZ2V/3ImTeFGH+)

**Comment by orta** [comment]
interesting, I think we should cover this case, thanks!

**Comment by orta** [comment]
We fixed this :+1:
