### ISSUE TITLE
The phrase 'pars' appear to break search

### ISSUE THREAD

**Issue by lazerwalker** [CocoaPods/cocoapods.org#121]
I recently tried to search for "parse", but encountered a pretty bizarre bug. If I enter "par", I get valid results. But the moment I enter an 's', so the search term is 'pars', a JS error occurs (stack trace below, although perhaps  not so useful with minified source) and the new search doesn't go through. This also happens if I try to enter anything after the s (e.g. "parse"). Works fine if I enter a letter that's not an 's' (e.g. "pare" or "park"), and I couldn't manually trigger with any other search terms. "Pars" fails consistently for me, though. 

This is hitting cocoapods.org (i.e. not a beta/staging site), on Safari / OS X 10.10.2.

Any thoughts?

![screen shot 2015-02-06 at 12 57 04](https://cloud.githubusercontent.com/assets/821238/6079015/09cf18fc-ae00-11e4-9349-95ed983c3a7e.png)

**Comment by lazerwalker** [comment]
The easiest way to reproduce: going directly to http://cocoapods.org/?q=pars is triggering this for me both in Safari and Chrome.

**Comment by floere** [comment]
Thanks Mike! A value for a source (git: ... or http: ...) is missing. I'll look into it.

**Comment by floere** [comment]
Ok, it's something that comes on the second page when searching for http://cocoapods.org/?q=name%3Apar

**Comment by floere** [comment]
And it's a pod which does not have a summary with parse in it: http://cocoapods.org/?q=summary%3Aparse

**Comment by floere** [comment]
It's one with fs in it: http://cocoapods.org/?q=Fs*%20pars

**Comment by floere** [comment]
In its name: http://cocoapods.org/?q=name%3AFs*%20pars

**Comment by floere** [comment]
Got it: http://cocoapods.org/?q=fsargumentparser

**Comment by floere** [comment]
Done. http://cocoapods.org/?q=pars

Some pods have bad data, and we are/were not defensive enough yet.

Thanks for the issue!

**Comment by lazerwalker** [comment]
:+1: Awesome, thanks!
