### ISSUE TITLE
About page text hard to read

### ISSUE THREAD

**Issue by Kapin** [CocoaPods/cocoapods.org#122]
![text](https://cloud.githubusercontent.com/assets/995382/6260303/99dfe332-b791-11e4-8c9e-441f9acc41d7.PNG)

The "Thousands of CocoaPods" part is difficult to read over the design in the background. 

cc/@orta

**Comment by orta** [comment]
Only if you have a cinema display at full screen, figured no-one does this. Except you, obv ;)

Open to a PR from someone, but unlikely to do so myself.
