### ISSUE TITLE
List of most popular pods

### ISSUE THREAD

**Issue by rinatkhanov** [CocoaPods/cocoapods.org#123]
I think it'd be useful for newcomers to iOS development / CocoaPods to have a list of most popular pods (sorted by a number of installations or Github stars — not sure if this is reasonably easy to implement with current setup). 

As a side note, this kind of page appears when you search for empty string on [Rubygems](https://rubygems.org/search?utf8=✓&query=).

**Comment by orta** [comment]
There's a pretty good site that does this already, http://cocoapods.wantedly.com

We've strayed away from pure stat ranking as they don't provide any value other than encouraging them to be gamed. We've been experimenting with a series of [ideas around quality](https://github.com/CocoaPods/cocoadocs-api/blob/master/quality_modifiers.rb) that might work in a ranking style, but for now. No.
