### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods.org#128]
Does the cert for trunk cover this website?

**Comment by alloy** [comment]
No, unfortunately it only covers the trunk subdomain. You'd need a wildcard cert to support _any_ domain.

**Comment by orta** [comment]
Cool cool

**Comment by kylef** [comment]
As I mentioned before, there is also a $20 fee on Heroku to add an TLS endpoint to each application. Considering we have (web, search, guides, blog, trunk, metrics, feeds) that's easily a lot of money each month to have TLS. I don't think it's worth the cost.

**Comment by orta** [comment]
It's worth it for `cocoapods.org` - we should be protecting the privacy of ourselves and everyone else.

**Comment by orta** [comment]
I don't mind about the other things, maybe I need it for CocoaDocs too.

**Comment by orta** [comment]
@kylef grabbed me on chat, given that not all our infrastructure can be SSL'd it'd mean that we'd only get a partial coverage leaking most of the useful stuff.
