### ISSUE TITLE
⌘+click on a pod link no longer opens in new tab

### ISSUE THREAD

**Issue by cameronehrlich** [CocoaPods/cocoapods.org#131]
It used to be that one could search for a pod, be presented with a list of search results, and then ⌘+click the ones they wanted to explore further into new tabs.  This was a big part of my workflow and I miss it a lot.  Am I the only one?  Perhaps there could be an additional little icon that links to the given pod's github repo?

**Comment by orta** [comment]
I think cmd+click can open the pod page directly ( there's a big prominent github link from there too ) in another tab, just need to check if alt/ctrl/cmd are on the click event then return.

**Comment by cameronehrlich** [comment]
:+1:
