### ISSUE TITLE
Show Logic behind Quality Estimate

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods.org#134]
![desktop pods page](https://cloud.githubusercontent.com/assets/49038/6994499/5ea1c0d4-daea-11e4-87a0-9d89b8250794.png)

`/pods/ORStackView/quality`  ?

**Comment by orta** [comment]
Hook up a cocoapods page that parses this metadata: https://cocoadocs-api-cocoapods-org.herokuapp.com/pods/ORStackView/stats

**Comment by kylef** [comment]
This is pretty cool :+1:.

**Comment by orta** [comment]
only show things that apply for the pod, if this feels weird, then we can find a way to show the ones that don't also.
