### ISSUE TITLE
Pod detail title's are getting clipped

### ISSUE THREAD

**Issue by kylef** [CocoaPods/cocoapods.org#136]
Seems to be a slight alignment issue, `g`, `j` etc are getting clipped at the bottom.

![screen shot 2015-04-07 at 14 02 50](https://cloud.githubusercontent.com/assets/44164/7023668/e6b2d5da-dd2e-11e4-88de-e9497464679d.png)

**Comment by orta** [comment]
![screen shot 2015-05-31 at 19 04 40](https://cloud.githubusercontent.com/assets/49038/7904422/eb02cb9a-07c7-11e5-9cc0-3ebca787e89b.png)

This is looking fixed on my current version.

**Comment by kylef** [comment]
You sure, here's a screenshot I just taken: 

![screen shot 2015-06-01 at 07 53 08](https://cloud.githubusercontent.com/assets/44164/7915575/47302a00-0833-11e5-9dfb-9235a5559a8e.png)

**Comment by orta** [comment]
Looks like my version of that is also correct, will try and guesstimate a fix

**Comment by segiddins** [comment]
Just let the overflow show?

**Comment by orta** [comment]
#212 might have a fix for this

**Comment by kylef** [comment]
Confirmed.
