### ISSUE TITLE
Specs removed from the master repo still appear in search

### ISSUE THREAD

**Issue by mhuusko5** [CocoaPods/cocoapods.org#139]
UILabel-M5FillFrame, UIStoryboardSegue-M5LinkedStoryboard, and NSPointerArray-M5Additions have been removed from the master spec repo, but still exist/are searchable on cocoapods.org.

**Comment by floere** [comment]
Thanks for the issue - how have they been removed?

**Comment by orta** [comment]
https://github.com/CocoaPods/Specs/pull/13050/files

looks like we probably have to go flag them as deleted in the production db

**Comment by floere** [comment]
Yes, we currently only react to modified and added specs: https://github.com/CocoaPods/trunk.cocoapods.org/blob/master/app/controllers/hooks_controller.rb#L66-L79

**Comment by orta** [comment]
There are other threads about this mainly on trunk, where the responsibly lays -  https://github.com/cocoapods/trunk.cocoapods.org/issues 
e.g. https://github.com/CocoaPods/trunk.cocoapods.org/issues/145

closing cause cocoapods.org cannot do anything here
