### ISSUE TITLE
Search cut off on iPad

### ISSUE THREAD

**Issue by squarefrog** [CocoaPods/cocoapods.org#141]
See https://github.com/CocoaPods/cocoadocs.org/issues/332

**Comment by orta** [comment]
I tested this on the iOS8 sim earlier and it looked fine

**Comment by squarefrog** [comment]
I suspect that's due to WebKit differences between desktop and mobile safari. 

If I use desktop safari at 1024x768, it's fine. With mobile safari on iPad it's as pictured. 

I've literally just been playing with it and come to that conclusion.

**Comment by squarefrog** [comment]
It could be that something needs resetting for iPad is there a global CSS reset file?

**Comment by orta** [comment]
grabbed an iPad ( 8.3) and its looking fine also, do you have an old OS?

**Comment by squarefrog** [comment]
8.2

**Comment by squarefrog** [comment]
![image](https://cloud.githubusercontent.com/assets/343450/7355983/6d12ddf2-ed1d-11e4-9bda-2e051750ca3f.jpg)
![image](https://cloud.githubusercontent.com/assets/343450/7355985/6d17b7c8-ed1d-11e4-884c-0fd52a98d247.jpg)

Well that's weird...

**Comment by squarefrog** [comment]
Sorry - had to delete my previous post as it contained my iPads serial. 

Just to confirm I'm on 8.3 iPad 3 and still get the cutoff.

**Comment by orta** [comment]
ah, it's an orientation bug, if portrait it happens, if landscape it doesn't :+1:

**Comment by squarefrog** [comment]
Makes sense. In portrait it gets squashed by the `@max-width:768px` iphone media query.

**Comment by floere** [comment]
@squarefrog Still an issue?

**Comment by squarefrog** [comment]
![image](https://cloud.githubusercontent.com/assets/343450/10894682/0fbc9d26-81a8-11e5-8449-ecfc5bf29e61.png)

Only in landscape

**Comment by floere** [comment]
Still an issue 😭Thanks for the quick feedback! :+1:

**Comment by squarefrog** [comment]
No problem, thanks for the fix. I had completely forgotten about this.

**Comment by floere** [comment]
@squarefrog Cheers! :rocket:
