### ISSUE TITLE
Improve support for non-github pods

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods.org#152]
This line is likely to be the problem, https://github.com/CocoaPods/cocoapods.org/blob/master/app.rb#L135

**Comment by k0nserv** [comment]
Yeah that should probably be a left join, what are the symtoms of the problem? I'll look into fixing it

**Comment by k0nserv** [comment]
Close?

**Comment by orta** [comment]
Yeah I think so, this https://github.com/CocoaPods/cocoapods.org/commit/9a803d98a98e35b4b27833c9a6ef7a45c565c665 wrapped up a bunch of that.
