### ISSUE TITLE
Mouse middle-click broken in search results page

### ISSUE THREAD

**Issue by fluidsonic** [CocoaPods/cocoapods.org#153]
Browsers allow a mouse middle-click to open a link in a new tab (just like Cmd + left-click). This does no longer work for Pods on the [CocoaPods search results page](https://cocoapods.org/?q=addressbook). Instead the Pod page will be opened through JavaScript in the same page.

I prefer to open all relevant Pods in new tabs using middle-mouse clicks and then go through them one after the other. This is no longer possible due to this issue.

**Comment by orta** [comment]
This is in with the next major deploy of the website.
