### ISSUE TITLE
GoogleMaps doesn't have listing, redirects to homepage

### ISSUE THREAD

**Issue by beriberikix** [CocoaPods/cocoapods.org#155]
I'm trying to figure out if this is user error or not. We uploaded [this spec](https://github.com/CocoaPods/Specs/blob/master/Specs/GoogleMaps/1.9.2/GoogleMaps.podspec.json) via Trunk. A search for it on cocoapods.org will return [a response](https://cocoapods.org/?q=name%3A%22googlemaps%22) but the link seems to go to the listed homepage. Navigating to https://cocoapods.org/pods/GoogleMaps also redirects.

Any obvious mistakes? Thanks!

**Comment by floere** [comment]
This is a problem on our side – I've ramped up the number of dynos on Heroku in preparation for an event in two days, but our "update indexes on ping from Github" infrastructure only works with a single dyno running – one of the issues I did not consider beforehand. I'll pull it down again to 1 dyno.

Thanks for reporting!

**Comment by floere** [comment]
P.S: It does appear now. Cheers!

**Comment by beriberikix** [comment]
Hmm, it seems to still be redirecting.

**Comment by floere** [comment]
@beriberikix Sorry, completely misread the issue text!

**Comment by orta** [comment]
I got this, turns out there was a divide by zero error in CocoaDocs, fixed and re-deployed GoogleMaps. FWIW, a README in your zip would be nice ;)

**Comment by beriberikix** [comment]
Thanks! I'm also seeing it on https://cocoapods.org/pods/GoogleIDFASupport - same issue?

I'll file an internal bug about the README :)

**Comment by orta** [comment]
Yep, re-parsed - https://cocoapods.org/pods/GoogleIDFASupport

When I get into my office tomorrow, I'll set my spare box running all un-parsed Docs as this bug must have existed for a few months.

**Comment by beriberikix** [comment]
Cool, thanks!

**Comment by beriberikix** [comment]
We just released a new Pod that has the same issue again: https://cocoapods.org/pods/GoogleAppIndexing. I suspect it is also missing a README :/

Good news is that we've added a lint rule (though this went through after the rule was added.)

**Comment by orta** [comment]
Yep, I've fixed it :+1:

**Comment by beriberikix** [comment]
:+1:

**Comment by ryot** [comment]
I'm having the same issue with AreaMetricsSDK, which I pushed via trunk yesterday afternoon.

**Comment by yasirmturk** [comment]
same issue https://cocoapods.org/pods/OpenALPRSwift
