### ISSUE TITLE
Octocat icon should be clickable on pod pages

### ISSUE THREAD

**Issue by segiddins** [CocoaPods/cocoapods.org#158]

**Comment by floere** [comment]
Not enough supportive material provided 😉 Why _do_ we even have GH branding there?

**Comment by kylef** [comment]
I think @segiddins was saying that the Octocat in the below screenshot should be tappable:

![screen shot 2015-11-02 at 14 00 43](https://cloud.githubusercontent.com/assets/44164/10895655/2bf59a26-816a-11e5-94e2-46aa2b1aded7.png)

**Comment by floere** [comment]
@kylef I know. I want to close issues, however, and nobody cares enough about this.

**Comment by kylef** [comment]
@floere, closing is fine. I didn't re-open. Was just adding sufficient information to the ticket for others to decipher what it means.

**Comment by floere** [comment]
@kylef I see, thanks 😊
