### ISSUE TITLE
Pod page shows the wrong content

### ISSUE THREAD

**Issue by jschmid** [CocoaPods/cocoapods.org#162]
Currently, if you look at the [JCDialPad page](https://cocoapods.org/pods/JCDialPad), you will see the content of [ABPadLockScreen](https://cocoapods.org/pods/ABPadLockScreen).

![screen shot 2015-05-27 at 09 33 23](https://cloud.githubusercontent.com/assets/574168/7831077/7773edd4-0453-11e5-988c-6d45c085c59f.png)

This might be the result of a concurrency error in the page generation. Let me explain:
- I did a search for [keypad](https://cocoapods.org/?q=keypad) which yield two results, ABPadLockScreen and JCDialPad.
- I opened in a new tab each pod's page. I opened them quickly. 

I guess there is some problem in page generation and now that the page is cached you always see the wrong content.

**Comment by orta** [comment]
Interesting, I've not seen this before. And re-parsing it doesn't seem to help.

**Comment by floere** [comment]
@orta Any idea what the issue could be? Should we do a review? (Or, you could point me at some code for a review)

**Comment by kylef** [comment]
This may not be a code problem, considering there is no authentication on the API call from CocoaDocs to the CocoaDocs API it would be extremely simple for anyone to push content to any pod detail page.

To prove this, see https://cocoapods.org/pods/MFStoryboardPushSegue where I've pushed metadata for QueryKit to another of my pods without using any access tokens.

**Comment by floere** [comment]
@kylef Good point. I assumed it was a code issue due to the reparsing not helping.

**Comment by kylef** [comment]
@floere Oh right, I went to the page and saw it was correct now, assuming the rep-parse did succeed.

**Comment by floere** [comment]
@kylef It's not correct, though.

**Comment by orta** [comment]
Since then there's been authentication added to the request, and the process is simpler - closing.
