### ISSUE TITLE
suggestion: direct link to the (github) project

### ISSUE THREAD

**Issue by colasjojo** [CocoaPods/cocoapods.org#163]
A suggestion:

On the result page, for each result add a button that opens a new tab to the github project (if it exists).

Thanks for your great work.

**Comment by orta** [comment]
All results, that can have a giithub button, have one on the expanded version.

**Comment by colasjojo** [comment]
@orta I meant a github button but in the list display (not the expanded version).

**Comment by orta** [comment]
Yeah, fair enough.
