### ISSUE TITLE
Owner page without any pods looks lonely

### ISSUE THREAD

**Issue by kylef** [CocoaPods/cocoapods.org#165]
Example: http://cocoapods.org/owners/2

Steps to resolve this problem:

- @floere to make some pods
- We show "This author doesn't yet have any pods" and a link to get started?

**Comment by floere** [comment]
How about a motivational quote? "It does not matter how slowly you go as long as you do not stop trying to make a pod."

**Comment by floere** [comment]
~~@floere to make some pods~~ I have a status to defend!

**Comment by neonichu** [comment]
Should use some orta GIFs, e.g.

![](https://ortastuff.s3.amazonaws.com/gifs/bug-hunting.gif)

**Comment by floere** [comment]
:clap:

**Comment by floere** [comment]
I think if somebody has an owner page, that person knows how to get started.

**Comment by kylef** [comment]
Agreed, also we have a new "0 Pods" screen so it's no longer an empty screen.

![screen shot 2015-11-02 at 13 46 14](https://cloud.githubusercontent.com/assets/44164/10895290/4797a6c2-8168-11e5-8ac5-b97b4ec79022.png)

**Comment by floere** [comment]
Exactamundo 😊Cheers!
