### ISSUE TITLE
Minimize a Pod

### ISSUE THREAD

**Issue by civilordergone** [CocoaPods/cocoapods.org#172]
How on earth do you minimize a pod when it's expanded???

You guys use to have this functionality and it made browsing the site a million times easier because the description eats up a ton of space.  Clicking the title use to do this.

Bring back the toggle!!!

**Comment by orta** [comment]
Wow, I just got around to reading this issue. @civilordergone this really isn't how you ask for features. Be nicer in your expectations of other people's time.

Regardless of this, I built this today.

**Comment by civilordergone** [comment]
What did I say that was rude?  It's not like I was hounding you down @orta to implement it.  
Someone on IRC recommended that I open an issue on github for the feature request.

I was just merely being enthusiastic about the previous UX [that made browsing the site easy]. I understand this is an open-source project and people are using their free-time to build something useful.
