### ISSUE TITLE
Quality Estimates should incorporate wiki links 

### ISSUE THREAD

**Issue by ketzusaka** [CocoaPods/cocoapods.org#173]
Many projects prefer to have a small README.md with links to their wiki to give more indepth documentation. This gives a nice segmentation between the code and tutorials/documentation about the library.

Currently, it seems that the quality estimates only look into the size of the README.md file itself; It should do some link evaluation (specifically to the wiki of the project) to determine the amount of documentation before applying the "Minimal README" or "Great README" metrics.

**Comment by orta** [comment]
I've been wondering about this, when I look at the documentation for RxSwift - it's all inside some markdown files in the repo too. We already have [support in CocoaDocs](http://cocoadocs.org/readme/) for Objective-C projects to use custom markdown links as a part of their documentation. I'd also like to see it in CocoaPods.

**Comment by orta** [comment]
We now don't punish people with bad READMEs if they have a `documentation_url` set up. So if there is extra documentation in the wiki, this can be referred to.
