### ISSUE TITLE
About page shouldn't break words

### ISSUE THREAD

**Issue by kylef** [CocoaPods/cocoapods.org#174]
![screen shot 2015-06-17 at 13 50 14](https://cloud.githubusercontent.com/assets/44164/8218437/cb940c96-14f7-11e5-9766-d32957830e4f.png)

For some reason `pod i` and `nstall` along with `pod upd` and `ate FLKAutoLayout` are broken onto separate lines mid way though the commands. We should keep these words together, and ideally keep commands on a single line.

https://cocoapods.org/about

**Comment by k0nserv** [comment]
@kylef this should have been resolved now

**Comment by orta** [comment]
It is, confirmed.
