### ISSUE TITLE
Update CoC to match the one we have on GH

### ISSUE THREAD

**Issue by neonichu** [CocoaPods/cocoapods.org#177]
Let's wait for CocoaPods/CocoaPods#3705 to be merged and from then on keep them in sync.

**Comment by neonichu** [comment]
By "in sync" I mean don't have them conflict in wording, not necessarily identical. As the GH CoC mentions events and meetups as well, they should be consistent.

**Comment by floere** [comment]
@neonichu It's merged. Sync?

**Comment by floere** [comment]
@neonichu Can we close this one?

**Comment by orta** [comment]
Yep
