### ISSUE TITLE
Direct repo URL produces Internal Server Error

### ISSUE THREAD

**Issue by Cocoanetics** [CocoaPods/cocoapods.org#179]
Steps to repro:

1. Go to http://cocoapods.org/pods/DTCoreText

Expected result:

- stats page of my component

Actual result:

- A blank page showing only "Internal Server Error"

**Comment by orta** [comment]
Thanks! Fixed!
I made some changes to one of the quality metrics, and renamed it - breaking the site.

**Comment by orta** [comment]
https://github.com/CocoaPods/cocoapods.org/commit/b474d349a8c69b51aec4f2ea2f46bc329b060eee

**Comment by empitechathu** [comment]
Yes mee too gettign same error here
