### ISSUE TITLE
Pod detail page (and inline version) fail to load with 500 Internal Server Error

### ISSUE THREAD

**Issue by Thomvis** [CocoaPods/cocoapods.org#180]
When searching for pods, I am currently not able to tap on it to view more details. 

I see that the `/inline` link (e.g. [https://cocoapods.org/pods/BrightFutures/inline](https://cocoapods.org/pods/BrightFutures/inline)) fails with a 500 Internal Server error. 

The same goes for the detail page itself: https://cocoapods.org/pods/BrightFutures.

It seems to happen no matter which Pod you select.

**Comment by orta** [comment]
:+1: I fixed this with https://github.com/CocoaPods/cocoapods.org/commit/b474d349a8c69b51aec4f2ea2f46bc329b060eee
