### ISSUE TITLE
"license": {     "type": "Affero GNU GPL v3" is show as simply 'GPL V3'

### ISSUE THREAD

**Issue by jogu** [CocoaPods/cocoapods.org#181]
Hi there,

I just uploaded a new pod spec for MuPDF.

The pod spec has:

      "license": {
        "type": "Affero GNU GPL v3",
        "file": "COPYING"
      },

but https://cocoapods.org/pods/MuPDF shows:

License: GPL 3

which is technically incorrect, as the Affero GPLv3 is not compatible with the normal GPLv3.

If I did something please let me know.

Thanks

Joseph

**Comment by orta** [comment]
No worries, we'd happily accept a PR adding it to the list of licenses & their urls: https://github.com/CocoaPods/cocoadocs.org/blob/master/classes/spec_extensions.rb#L73

**Comment by jogu** [comment]
Great, thanks for pointing me at the right bit of code!

I've gone ahead and created a pull request:

https://github.com/CocoaPods/cocoadocs.org/pull/366

**Comment by orta** [comment]
This'll get updated on the next release of your pod, all this data generation happens then rather than at runtime.

**Comment by jogu** [comment]
Great, thank you @orta

**Comment by jogu** [comment]
@orta I pushed a new version of the pod a few days back but https://cocoapods.org/?q=mupdf still shows GPLv3 instead of AGPL - Any idea what is wrong? Thanks!
