### ISSUE TITLE
Tested property not handled correctly for closed source pods

### ISSUE THREAD

**Issue by jayneflux** [CocoaPods/cocoapods.org#182]
Closed source pods currently say 'no tests' or incorrectly use the included sample code's tests to show that a pod has tests.

Such pods should not be getting the quality rating points for being tested but I propose that we make that field listed as 'Unknown' instead of 'No tests' in order to be more representative of the true status of the pods.

**Comment by orta** [comment]
This feels very reasonable to me, I added `is_vendored_framework` to [metrics](http://metrics.cocoapods.org/api/v1/pods/Expecta) a month back to start accommodating this kind of issue.

**Comment by orta** [comment]
This should be :+1: now with https://github.com/CocoaPods/cocoapods.org/commit/9a803d98a98e35b4b27833c9a6ef7a45c565c665
