### ISSUE TITLE
The "Specs and the Specs Repo" has invalid specs as examples

### ISSUE THREAD

**Issue by ghthor** [CocoaPods/cocoapods.org#184]
The first [spec](https://guides.cocoapods.org/making/specs-and-specs-repo.html) shown has invalid ruby syntax.

**Comment by segiddins** [comment]
This belongs over on https://github.com/CocoaPods/guides.cocoapods.org, and a PR with a fix would be much appreciated!

**Comment by ghthor** [comment]
[done](https://github.com/CocoaPods/guides.cocoapods.org/pull/79)

Sorry for the misplaced issue.
