### ISSUE TITLE
No "CHANGELOG" credit for UnzipKit

### ISSUE THREAD

**Issue by abbeycode** [CocoaPods/cocoapods.org#188]
UnzipKit's [quality page](https://cocoapods.org/pods/UnzipKit/quality) doesn't give credit for having a CHANGELOG, but it [does, here](https://github.com/abbeycode/UnzipKit/blob/master/CHANGELOG.md).

**Comment by segiddins** [comment]
@abbeycode we haven't gone back to re-parse old docs yet, so the CHANGELOG will show up when you next release a version

**Comment by abbeycode** [comment]
:+1:

**Comment by orta** [comment]
Yeah, I started it on Friday, and it's got to `JWFolders` so far. It'll be a while alas. By the end of the week from the looks of things.
