### ISSUE TITLE
Experiment with San Francisco as a body font

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods.org#191]
Re: https://twitter.com/rehatkat/status/628248508370436096

**Comment by clooth** [comment]
Are there still problems with apple's stance on how you're allowed to use it?

**Comment by orta** [comment]
I was thinking of using https://www.webkit.org/blog/3709/using-the-system-font-in-web-content/

**Comment by clooth** [comment]
That's doable yeah. I just don't know if they changed their policy for webfonts yet. Would be neater to use it as the de-facto font. Windows' font rendering sucks though.

**Comment by orta** [comment]
There are more Windows sessions on CocoaPods.org than iOS. So it's worth keep them in mind ( 5.5% vs 4.6%. )

**Comment by clooth** [comment]
Yeah, then it's okay. You're speaking of mobile visitors?

**Comment by floere** [comment]
@orta @clooth Is this still a valid issue given the number of Windows visitors we have?

**Comment by kylef** [comment]
We can still use San Francisco as a font with windows. We can offer a web-font for windows and platforms that don't have San Francisco. Example: https://gist.github.com/sotayamashita/8f19fb312dc09cfa505e

I think this is permitted, but we would need to verify with the terms of service of the font.

**Comment by floere** [comment]
From the Apple Fonts page:

```
2. Permitted License Uses and Restrictions.
A. Limited License. Subject to the terms of this License, you may use the Apple Font solely for creating mock-ups of user interfaces to be used in software products running on Apple’s iOS or OS X operating systems, as applicable. The foregoing right includes the right to show the Apple Font in screen shots, images, mock-ups or other depictions, digital and/or print, of such software products running solely on iOS or OS X.
```

That's a big no-no. Closing.
