### ISSUE TITLE
Objective-c language detected for a swift project

### ISSUE THREAD

**Issue by jduquennoy** [CocoaPods/cocoapods.org#194]
Hello cocoapods team !

I am maintaining the Log4swift cocoapod (https://cocoapods.org/pods/Log4swift).
This project is mostly written in swift, except for one wrapper and a third party source file, that are objective-c.

GitHub reports more than 50% written in swift, nevertheless, cocoapod's metrics system consider it as an objective-c project.
Is that normal, is that expected ?

Thanks for your attention,

Jerome

**Comment by orta** [comment]
When we run [CLOC](http://cloc.sourceforge.net) on the files in your Podspec we get this:
```
{:language=>"Objective C", :files=>2, :comments=>349, :lines_of_code=>2407}
{:language=>"Swift", :files=>19, :comments=>524, :lines_of_code=>903}
{:language=>"C/C++ Header", :files=>5, :comments=>272, :lines_of_code=>190}
{:language=>"SUM", :files=>26, :comments=>1145, :lines_of_code=>3500}
```

Which means that, as a majority, your library is considered Objective-C, even though the public interface for your library is Swift.

**Comment by segiddins** [comment]
(Presumably we're going by lines of code rather than files)

**Comment by orta** [comment]
It looks like you're vending NSLogger, given that it is it's [own Pod](https://cocoapods.org/pods/NSLogger), switching to using it as a dependency instead of integrating it into your app would get you the results you're after.

**Comment by jduquennoy** [comment]
That is a great idea.
I'll update to do that, indeed.
Thanks for your very fast answer :-).

Jerome
