### ISSUE TITLE
Add Community Impact section to Owner's page

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods.org#195]
![screen shot 2015-08-14 at 9 22 03 pm](https://cloud.githubusercontent.com/assets/49038/9286814/a8613388-42ca-11e5-8159-c7d176321027.png)

* Pods is bigger, cause it's always gonna be substantially lower
* QI score is is all Pods' `cocoadocs` table `quality_estimate` average
* Apps Touched is all Pods' `stats` table's `app_total` combined
* Combined Downloads is all Pods' `stats` table's `download_total` combined
* Combined Stargazers is all Pods' `github` table's `stargazers` combined. This should be hidden if 0 because they don't use github.
* Total Lines of Code is all Pods' `cocoadocs` table's `total_lines_of_code ` combined

**Comment by kylef** [comment]
This is awesome :ok_hand:

**Comment by neonichu** [comment]
:sparkles: :sparkling_heart: :sparkles:
