### ISSUE TITLE
Back button / back to result list

### ISSUE THREAD

**Issue by florianbuerger** [CocoaPods/cocoapods.org#196]
When expanding a pod, there is no way to go back to the result list. This is worse when the README is really long. You habe to scroll through it to see the next search result. 

I'd love to use the browsers back button to minimize the pod and go to the list.

Kinda relates to #172.

**Comment by orta** [comment]
I'm a bit wary about this, we'd have an awful lot of back/forward state changes going on. I've added a close button so far, let's see if that's enough.

**Comment by segiddins** [comment]
Agree that the close button is sufficient, I really don't want to deal with the browser history stuff

**Comment by floere** [comment]
Let's go with the close button for now – please reopen, should it be too painful to use.
