### ISSUE TITLE
GitHub section not updating

### ISSUE THREAD

**Issue by hkellaway** [CocoaPods/cocoapods.org#198]
i've noticed that the stats under the GitHub section are not updating. for example, the latest version i pushed for this pod https://cocoapods.org/pods/Gloss today shows:

![screen shot 2015-08-22 at 1 47 06 pm](https://cloud.githubusercontent.com/assets/5456481/9425169/4e1154e8-48d4-11e5-990a-e8f8fbb76aab.png)

despite their being values `148`, `6`, `6`, `1`, `3`, `0` for the stats respectively

**Comment by segiddins** [comment]
The metrics updater only runs about once a day per pod, see https://github.com/CocoaPods/metrics.cocoapods.org for the relevant web app.

**Comment by orta** [comment]
re: http://metrics.cocoapods.org/api/v1/pods/Gloss
the data totally feels off:
```
"github": {
"subscribers": 1,
"stargazers": 0,
"forks": 0,
"contributors": 1,
"open_issues": 0,
"open_pull_requests": 0,
"created_at": "2015-08-17 02:34:52 UTC",
"updated_at": null,
"language": "Swift",
"closed_issues": 0,
"closed_pull_requests": 19
},
```

**Comment by segiddins** [comment]
Either way, the issue is in the wrong repo.
