### ISSUE TITLE
Search with dash

### ISSUE THREAD

**Issue by krzyzanowskim** [CocoaPods/cocoapods.org#199]
"google-api-client" https://cocoapods.org/?q=google-api-client
find nothing, but there is one found by google http://cocoapods.org/pods/Google-API-Client
![screen shot 2015-08-26 at 17 20 15](https://cloud.githubusercontent.com/assets/758033/9497732/bb9cf66c-4c16-11e5-9134-d9537a911fae.png)

**Comment by segiddins** [comment]
I'm not seeing a semicolon?

**Comment by krzyzanowskim** [comment]
I meant dash ;-)

**Comment by segiddins** [comment]
Hm, it seems to be working now...

**Comment by krzyzanowskim** [comment]
yes it is now, strange!

**Comment by orta** [comment]
I wonder if the search engine was in the restarting process, it can take a while to generate all the data.

**Comment by orta** [comment]
![screen shot 2015-08-26 at 11 31 40 am](https://cloud.githubusercontent.com/assets/49038/9498082/09526f6c-4be6-11e5-98f2-9ff8e525d859.png)
@floere

**Comment by floere** [comment]
Hey all! Search restarts once per day (Heroku does that automatically) and when it does, search has to reindex on the fly. I'm thinking of adding a "percentage indexed" attribute to the answer though to help API users. Cheers from my holidays! 🚀

**Comment by orta** [comment]
We've got the percentage indexed in. Not doing anything with the API yet.
