### ISSUE TITLE
CocoaPods version on the homepage?

### ISSUE THREAD

**Issue by imkevinxu** [CocoaPods/cocoapods.org#203]
Can there be a small piece of text on the homepage that says what's the latest stable version? I always check the homepage of a library to see what's the latest version but for CocoaPods I keep having to dig through GitHhub

**Comment by orta** [comment]
I've wanted to start adding in some overall stats from the analytics and was going to make some copy changes here, will take this into account, think it's a great idea :+1:

**Comment by floere** [comment]
Would a link to https://rubygems.org/gems/cocoapods suffice?

**Comment by orta** [comment]
We have the latest gem in the Gemfile, so we can pull that out ( like we do for links to the CP mac app )

**Comment by floere** [comment]
@orta It's already pulled out for you. For example: `ruby -e 'gem "cocoapods-core"; as = Gem.loaded_specs["cocoapods-core"]; puts as.version'`.

But I'd still go with a link to https://rubygems.org/gems/cocoapods, as we'd have to restart the cocoapods.org web app each time we bump the version to have it be correct. And the link content is always up to date.
