### ISSUE TITLE
Bring back Average QI to Owners Page.

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods.org#204]
https://github.com/CocoaPods/cocoapods.org/pull/202 totally removed the commented out version.

**Comment by floere** [comment]
Yep. If it's worth doing, it's worth redoing, correctly (it did not work anyway).

**Comment by k0nserv** [comment]
So what was the problem with the old implementation?

**Comment by floere** [comment]
@k0nserv The issue was that the case where a user has 0 pods was not handled (but that was not an actual issue, as the code was commented out).
A good idea would be think about how to handle this special case (0 pods) generally – call to actions, getting started links etc.

**Comment by k0nserv** [comment]
Cant we just hide the value if the user has 0 pods for now? At least until @orta has the time to do design something for the completely empty case?

**Comment by floere** [comment]
Sure!

**Comment by orta** [comment]
we didn't show the value at all before @floere removed it, I wanted an average QI filled pod thing in the design but couldn't get it to feel right, so it was commented out.

**Comment by k0nserv** [comment]
So should I bring it back and hide it if the user has no pods then?

**Comment by orta** [comment]
Sure, take a stab at it! Please include some images with what it looks like in the PR :dancers:

**Comment by floere** [comment]
@k0nserv Do you need more infos for this?

**Comment by k0nserv** [comment]
No, just been sidetracked lately. I'll have a look at it

**Comment by floere** [comment]
@k0nserv This is done, right?

**Comment by k0nserv** [comment]
[It is](https://cocoapods.org/owners/1)

**Comment by floere** [comment]
Great :)
