### ISSUE TITLE
"Independently builds through Xcode" quality metric is often not correct applied

### ISSUE THREAD

**Issue by kylef** [CocoaPods/cocoapods.org#207]
I think this is due to Xcode version mismatch, perhaps we should rethink this metric as it is not reliable at all. Every pod I've tried that is actually independently build-able says it is not in CocoaPods.

##### Swift
- [Alamofire](http://cocoapods.org/pods/Alamofire/quality)
- [URITemplate](https://cocoapods.org/pods/URITemplate/quality)
- [WebLinking](https://cocoapods.org/pods/WebLinking/quality)
- [JSONWebToken](https://cocoapods.org/pods/JSONWebToken/quality)

##### Objective-C
- [AFNetworking](http://cocoapods.org/pods/AFNetworking/quality)

**Comment by orta** [comment]
I made it work on whether you mention Carthage in your README now as well. Should work fine in most of these cases with a re-parse.

**Comment by kylef** [comment]
@orta Alamofire does, and it doesn't show up, we did a 2.0.2 release yesterday.

**Comment by orta** [comment]
I shipped a bunch of fixes around this, Alamofire is now counted - and it didn't have to run the tool locally. Will see what AFNetworking look like.

**Comment by orta** [comment]
AFNetworking got:

```
*** No Cartfile.resolved found, updating dependencies
*** Cloning AFNetworking
*** Checking out AFNetworking at "2.6.0"
*** xcodebuild output can be found in /var/folders/mk/gxhr550d5mbcv5s9_f61x84h0000gn/T/carthage-xcodebuild.9bqv9H.log
*** Skipped building AFNetworking due to the error:
Dependency "AFNetworking" has no shared framework schemes
```

**Comment by floere** [comment]
@kylef @orta Can we close this one?

**Comment by kylef** [comment]
I don't think so, in general this is still a unreliable and a bunch of pods that are independently buildable says they are not independently buildable.

**Comment by floere** [comment]
@kylef @orta Should we then drop this metric until we can make it work?

**Comment by kylef** [comment]
To be honest, I don't think this should be a quality metric. With Swift becoming OSS, pods may not even target OS X/iOS. Just because these types of pod's don't have an Xcode project doesn't mean they are worse quality than the ones that do.

This metric is only for Cocoa related pods.

**Comment by floere** [comment]
@kylef So should we open a new issue to use this metric only for Cocoa related pods? Or move it to metrics and open one there to remove this metric? /cc @orta

**Comment by orta** [comment]
>  With Swift becoming OSS, pods may not even target OS X/iOS.

Think this is a legit reason. I'm happy to drop support (it's a nightmare for maintenance too)

**Comment by orta** [comment]
Alright, so, I think I want to keep track of support but hide that away in the db / `metrics.cocoapods.org` API, but remove it from the QIs.

**Comment by floere** [comment]
@orta Thanks! So this issue should be closed, and one opened on cocoadocs-api, iirc?

**Comment by orta** [comment]
yes

**Comment by floere** [comment]
:+1:
