### ISSUE TITLE
FR: add status monitoring

### ISSUE THREAD

**Issue by beriberikix** [CocoaPods/cocoapods.org#208]
It would be great to have a page like https://www.statuspage.io/ to let us know when the site goes down. Earlier today we saw a temporary outage of the site but not trunk or anything but it had us worried.

**Comment by orta** [comment]
We do: https://status.cocoapods.org

**Comment by orta** [comment]
Though I wonder if we can make this easier to find, maybe it should go in the footer every page at the bottom saying Status

**Comment by beriberikix** [comment]
you folks work fast! :rocket: I looked for it in the header or the readme, thanks for the pointer!

**Comment by orta** [comment]
I've put it in the footer :+1:
