### ISSUE TITLE
CSS bug cropping characters

### ISSUE THREAD

**Issue by beriberikix** [CocoaPods/cocoapods.org#210]
![screen shot 2015-09-24 at 5 53 30 pm](https://cloud.githubusercontent.com/assets/178376/10090558/ae2a9184-62e5-11e5-8dc5-66e723905c12.png)

Take a look at the lower-case g. Something needs some padding.

**Comment by beriberikix** [comment]
Changing the height is one approach.
![screen shot 2015-09-24 at 6 03 53 pm](https://cloud.githubusercontent.com/assets/178376/10090642/b4a99ffe-62e6-11e5-9176-9a508c55551a.png)

**Comment by orta** [comment]
I couldn't re-pro this earlier, so I just applied your fix outright. Let me know if it's now good.

**Comment by beriberikix** [comment]
Hmm, doesn't look like it is being applied. Also for not providing my system earlier!

OSX 10.10.5, MBA 13-inch, Mid 2013. Cr 45.0.2454.99 (64-bit)

![screen shot 2015-09-26 at 7 02 49 am](https://cloud.githubusercontent.com/assets/178376/10117910/b91f6b0e-641c-11e5-9a13-f6471e3aa778.png)

**Comment by orta** [comment]
:+1: will take another look next time I'm in the repo

**Comment by floere** [comment]
This is now fine.
