### ISSUE TITLE
Any idea why Changelog is in chronological order?

### ISSUE THREAD

**Issue by beriberikix** [CocoaPods/cocoapods.org#211]
We just starting out [publishing a changelog](http://cocoapods.org/pods/Google#changelog) and I noticed it was weirdly in chronological order. [AFNetworking](https://cocoapods.org/pods/AFNetworking#changelog) is in reverse chronological order (newest on top) as I would expect. Are we formatting something incorrectly?

**Comment by segiddins** [comment]
@beriberikix it's just using the exact markdown you've provided in the `CHANGELOG.md` file.

**Comment by beriberikix** [comment]
d'oh! Should have checked first. Will fix in the next one, thanks!
