### ISSUE TITLE
Add watchOS + tvOS to the search bar

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods.org#215]
https://github.com/CocoaPods/search.cocoapods.org/issues/98

**Comment by kylef** [comment]
Maybe this should become a dropdown since we now have 5 items?

- Any
- iOS
- OS X
- watchOS
- tvOS

![screen shot 2015-09-30 at 17 59 09](https://cloud.githubusercontent.com/assets/44164/10210546/fc672aea-679c-11e5-8546-2c9f2726b11b.png)

**Comment by floere** [comment]
@kylef I think we can take one more (not using a dropdown explains what it is in a lovely way).

**Comment by floere** [comment]
@orta has implemented this.
