### ISSUE TITLE
A "ghost" spec appears

### ISSUE THREAD

**Issue by seivan** [CocoaPods/cocoapods.org#219]
https://cocoapods.org/?q=SHSegue

will output

```
SHSegueBlocks 1.2.3
SHSegueBlock 1.0.0
```

There isn't a SHSegueBlock (sans s) in Specs/ (and shouldn't)

I also took a look at Specs/SHSegueBlocks and there isn't a 1.0.0 there either.

**Comment by floere** [comment]
Thanks for the issue! Sadly, we don't have too much auditing info on this pod, as `SHSegueBlock`, as well as `SHSegueBlocks` were created when we imported the Specs into Trunk.
My best assumption is that perhaps these specs were deleted from the Specs repo, and this was not mirrored in the database. There is a SHSegueBlocks 1.0.0 version in the Trunk database, but that could stem from the same issue (do you perhaps remember to have made a PR to remove a version from the Specs repo?).

**Comment by seivan** [comment]
My memory is a bit vague I *suspect* I've at some point a long time ago removed a ```SHSegueBlock``` (sans s) because a rename or a mistake. 
That's probably the issue here.

**Comment by floere** [comment]
I've removed it from Trunk. Cheers!
