### ISSUE TITLE
Duplicate in search result

### ISSUE THREAD

**Issue by spherefoundry** [CocoaPods/cocoapods.org#220]
When searching for my newly added pod (PLXImageManager) I get a duplicate entry for it when entering just PLX into the query (https://cocoapods.org/?q=PLX). To be specific, I get:

- PLXImageManager 3.0.0
- PLXImageManager 3.0.0
- PLXFrameLayout 0.2
- PLXVisualAttributeConstraints 1.0.0

Both link to the same expanded page: https://cocoapods.org/pods/PLXImageManager

**Comment by floere** [comment]
Thanks Antoni! That is a weird bug that I have not yet been able to reproduce, or explain – probably a timing-related bug.
