### ISSUE TITLE
My author page does not reference all my pods

### ISSUE THREAD

**Issue by yannickl** [CocoaPods/cocoapods.org#222]
Hi there,

I don't know why but my cocoapods [author page](https://cocoapods.org/owners/1251) does not reference my [DynamicButton pod](https://cocoapods.org/pods/DynamicButton).

The *Maintained by* link redirects correctly to my author page but the `DynamicButton` is not available.

Thank you for the great work! :+1:

**Comment by yannickl** [comment]
I have the same issue with my new [Slipflat pod](https://cocoapods.org/pods/Splitflap).

**Comment by orta** [comment]
I'm willing to bet this is because there's not GitHubs generated yet  http://metrics.cocoapods.org/api/v1/pods/Splitflap - we should not predicate showing a pod on this, likely this line of code in app.rb: 

```
    all_dbs = metrics.join(:stats_metrics).on(:id => :pod_id)
```

**Comment by yannickl** [comment]
Indeed the 2 pods that are not related to my profile have a nil *stats* value. However today the *github* stats are ready.

So the problem comes from the join between the *github stats* and the *cocoapods stats* when one of both are nil.

**Comment by orta** [comment]
interesting, thanks, I'll see if I can get to it on the weekend if not anyone else is welcome to take a look.

**Comment by orta** [comment]
https://github.com/CocoaPods/stats.cocoapods.org/pull/13 may have fix this, now every pod should have a row.

**Comment by yannickl** [comment]
Yes everything seems to work. Thank you! :+1:
