### ISSUE TITLE
Pod quality metrics punished if tooling fails/crashes/errors 

### ISSUE THREAD

**Issue by danthorpe** [CocoaPods/cocoapods.org#224]
Hi,

As I'm sure you're aware, in the last few weeks since Xcode 7.1 there have been some issues parsing documentation of Pods. 

Some of the quality metrics (the documentation ones) which get computed for a Pod rely on these. For a pod where the documentation analysis fails, the doc coverage gets reported as 0% and the Pod receives a -8 for "Badly Documented". For the creator of an open source framework, this can be really frustrating. I think for quality metrics to be applied to a project (such as documentation quality) it only makes sense that the tooling upon which the metric is based finishes successfully.

*So, I suggest that if Jazzy fails for some reason, or Github's APIs are down, then rather than punishing the quality of the pod - indicate that the metric is not available / score zero.*

Largely thanks to the combined work of everyone in the CP dev team, the "quality" of OSS by these metrics is very visible, and I applaud and thank you all for your efforts. I think your success in this now play a significant role in adoption, which in turn typically drives development and community. I take them very seriously, and I expect many other framework developers do too. With the release of Jazzy 0.4 it looks like the tooling is back on track - great work from everyone involved with CocoaPods! However, as is always the case with Apple, breaking changes are the norm, and some of these automated tools which rely on Xcode are always just a point release away from failure.

As it happens, jazzy 0.4 still crashes somewhere in xcodebuild generating docs for my framework, so until I can figure out what is causing that, https://cocoapods.org/pods/Money will continue to be "Badly Documented" - despite being ~ 60-70% documented, see (https://github.com/danthorpe/Money/blob/development/Money/Money.swift).

**Comment by segiddins** [comment]
A PR implementing this would be much appreciated!

**Comment by danthorpe** [comment]
Well, I'll be more than happy to submit a PR, I'm not much of a Ruby developer, nor do I have much familiarity with how CocoaPods services work, but I've been trying to find out where changes would need to be made. 

Figured out that the website gets the metrics from here https://github.com/CocoaPods/cocoadocs-api/blob/master/app.rb but this just reads/writes from/to a database. So, somewhere, a service POSTs some JSON here. I was thinking that this would be somewhere in https://github.com/CocoaPods/metrics.cocoapods.org, maybe cocoadocs_pod_metrics.rb, but, I'm not really sure what this does. 

It's a little confusing because there is cocoadocs-api which seems to be used to get the metrics which are displayed on a Pods page on the website, but there is also metrics.cocoapods.org which has API endpoints to gets the documentation metrics & more. But still not sure what service/tooling is responsible for calculating them. Looking in trunk now...

**Comment by segiddins** [comment]
CocoaDocs itself is what runs Jazzy

**Comment by orta** [comment]
Yeah, I think it might make sense to set a `-1` if we couldn't pull off documentation, then not apply the metrics if it's that.  IMO things are likely to get a bit worse before they get better as CocoaDocs consolidates on Jazzy for objc/swift in the future.

**Comment by danthorpe** [comment]
It does look like errors from Jazzy should be caught though right? https://github.com/CocoaPods/cocoadocs.org/blob/master/cocoadocs.rb#L449

But yeah, applying a -1 for "Documentation cannot be generated" seems like a good compromise to me. Does Ruby have optionals? Some kinda of `Bool?` seems like what we need here! :)

**Comment by orta** [comment]
Well, I was thinking of the doc% - generally speaking we use the knowledge that we have any [cocoadocs metrics](http://metrics.cocoapods.org/api/v1/pods/Money) as a sign of whether we could parse the docs. In theory, the only thing it does outside of actually generating docs is generating the `doc_percent`. It doesn't affect any of the other metrics CocoaDocs generates. 

Yeah, an optional would be nice here (as an Int/ for the `doc_percent`, but no ruby doesn't and I'm pretty sure the column in the db is not nullable. ) So it would probably need to be a `NSNotFound` :)

**Comment by danthorpe** [comment]
I see, so if the doc generation fails, the % is reported as a 0%. And you're suggesting that a -1% would be better - and indicate to not apply the "Badly Documented" metric. I get it.

**Comment by orta** [comment]
:star:

**Comment by orta** [comment]
OK, this is in
