### ISSUE TITLE
Multiple entries of the same spec

### ISSUE THREAD

**Issue by hfossli** [CocoaPods/cocoapods.org#226]
<img width="1211" alt="skjermbilde 2015-11-20 kl 14 01 47" src="https://cloud.githubusercontent.com/assets/3652587/11300445/68493a2c-8f8f-11e5-84cd-cb00183adc62.png">

**Comment by hfossli** [comment]
Also curios why that specific pod isn't expandable like the others.

**Comment by orta** [comment]
I can answer the latter, but not really the former: http://orta.io/rebase/why-cant-i-expand/

**Comment by hfossli** [comment]
Thanks!

**Comment by floere** [comment]
Closing this one, as @dbgrandi reports getting duplicates in the search engine JSON response, see https://github.com/CocoaPods/search.cocoapods.org/issues/97.
