### ISSUE TITLE
Link Pods directly to Github

### ISSUE THREAD

**Issue by kirualex** [CocoaPods/cocoapods.org#227]
Current system is very annoying, I always end up going to Github anyway to fork/star/clone/comment projects and having an unnecessary step in-between is frustrating.
It is even more when the website serves an Application Error.

**Comment by orta** [comment]
Hi, this isn't a very useful issue, can you please provide some steps to reproduce?

https://cocoapods.org/pods/FBSDKLoginKit is working fine for example

**Comment by kirualex** [comment]
1 - Search for FBSDK on cocoapods
2 - middle click (or cmd-click) one of the result
It opened a page on cocoapods.org. This is really annoying because I think probably everyone just want to go directly on the library website/github page.

Cocoapods referencing documentation was a bad idea in the first place (usability, updatability) but this is for another issue I guess.

**Comment by orta** [comment]
Ah, well, I'm afraid this is just something that we're going to disagree on @kirualex.

**Comment by kirualex** [comment]
Example issue : try with CocoaLumberjack pod. Integrated doc is lacking a whole block on Swift integration. 

Maybe having a 'github" button next to "expand" would be a good compromise? What do you think @orta?

**Comment by orta** [comment]
No, I'm happy with how the search results are shown, if you'd prefer one that does this there are alternatives like http://cocoapods.wantedly.com

The README is the most recent public release version, you see the README that they shipped in that release not what is on master. This is on purpose, it's the code you get when you do `pod "CocoaLumberjack"`.

**Comment by kirualex** [comment]
Oh my, http://cocoapods.wantedly.com is exactly what I needed, thanks!
