### ISSUE TITLE
Only search/show released pods.

### ISSUE THREAD

**Issue by floere** [CocoaPods/cocoapods.org#228]
Following RubyGems' lead we're moving to showing the latest stable version instead of the latest version including prerelease versions.

* [x] Search engine (https://github.com/CocoaPods/search.cocoapods.org/blob/master/lib/models/pod.rb#L85-L95).
* [x] CocoaDocs (https://github.com/CocoaPods/cocoadocs.org/pull/409).

Related: https://github.com/CocoaPods/search.cocoapods.org/issues/102

**Comment by floere** [comment]
Ping @orta – I assume CD needs to be changed. Anything else?

**Comment by alloy** [comment]
:+1:

**Comment by orta** [comment]
Cool, yeah, looks good but I'm afraid the hard work overall is in cocoadocs and all affected docs need reparsaing

**Comment by segiddins** [comment]
@orta iirc CocoaDocs already only uses stable versions? I remember implementing that about a year ago(https://github.com/CocoaPods/cocoadocs.org/pull/292)

**Comment by floere** [comment]
@segiddins Indeed!

Any reasons not to go ahead with this?

**Comment by orta** [comment]
It's the stats generators,  README/CHANGELOG parsing that will happen always  against the latest podspec that doesn't take the stable version into account

**Comment by segiddins** [comment]
@orta I can make a PR changing that today

**Comment by orta** [comment]
Sure. :)

You can run `rake run["cocoadocs doc #{space separated pods}"] locally to trigger a re-run for affected pods too, as an example. If it's more than a thousand or so though, I can run them locally on my spare cocoadocs machine.

**Comment by segiddins** [comment]
```
rake aborted!
Don't know how to build task 'run'
```

**Comment by orta** [comment]
Sorry, looks like it's the `exec` command. I think you can actually do this instead though;

``` sh
rake doc["names of pods with spaces"]
```

**Comment by floere** [comment]
Not sure I understand – what pieces on e.g. this page (https://cocoapods.org/pods/AFNetworking) are from the prerelease version? The version itself, but what else?

**Comment by floere** [comment]
@orta @segiddins ^

**Comment by segiddins** [comment]
@floere everything my PR on CocoaDocs changes

**Comment by floere** [comment]
@segiddins Thanks! Would you mind linking it here?

**Comment by segiddins** [comment]
https://github.com/CocoaPods/cocoadocs.org/pull/409

**Comment by aperechnev** [comment]
That would be great if pod authors will be able to point in the podspec file if they do want to show pre-release versions or not. A lot of libraries provide great functionality in pre-release version, while authors are afraid of making release for some reasons.

**Comment by orta** [comment]
We're probably not going to support that I'm afraid, people should be releasing real versions ( I totally understand the irony of this coming from the CP team )

**Comment by floere** [comment]
@aperechnev Re "afraid": We have to trust pod authors – if they have reasons to not release pod functionality, we just assume that they have good reasons.

Re "having a choice": Showing prerelease versions in some pods and not in others seems like a great way to confuse users (who would have to know about each pod's setting to know if the latest version may be a prerelease version). So I'd say we should stick to one way of doing things. Pod authors of course are super-free to promote prerelease versions via other channels.

**Comment by orta** [comment]
This is in on search

**Comment by floere** [comment]
Yep – I'll close.
