### ISSUE TITLE
Possible search issue

### ISSUE THREAD

**Issue by nwest** [CocoaPods/cocoapods.org#231]
Seems like showing the same result multiple (many) times is not ideal.

![screen shot 2015-12-08 at 2 17 56 pm](https://cloud.githubusercontent.com/assets/466674/11665861/7daf04ba-9db7-11e5-8aba-9df45473c864.png)

**Comment by floere** [comment]
You may be right ;)

**Comment by nwest** [comment]
Dupe of #226

**Comment by floere** [comment]
@nwest Thanks Nate – I'll close this one then.
