### ISSUE TITLE
undefined method `calculation_steps' for nil:NilClass

### ISSUE THREAD

**Issue by floere** [CocoaPods/cocoapods.org#234]
On https://cocoapods.org/pods/Google/quality:

```
2015-12-12 00:25:31.801933+00:00 heroku router - - at=info method=GET path="/pods/Google/quality" host=cocoapods.org request_id=a5d6fd1d-63c0-4f72-815f-bed680180c8b fwd="208.115.113.91,108.162.246.170" dyno=web.1 connect=0ms service=29ms status=500 bytes=332
» 12 Dec 2015 01:25:32.085 2015-12-12 00:25:31.799294+00:00 app web.1 - - NoMethodError - undefined method `calculation_steps' for nil:NilClass:
» 12 Dec 2015 01:25:32.086 2015-12-12 00:25:31.799298+00:00 app web.1 - - /app/views/pod_quality.slim:100:in `block in singleton class'
» 12 Dec 2015 01:25:32.086 2015-12-12 00:25:31.799299+00:00 app web.1 - - /app/views/pod_quality.slim:-1:in `instance_eval'
```

**Comment by orta** [comment]
This is someone taking down the metrics API - we might need to put rack attack on trunk, metrics and cocoa pods.org - thanks whoever has taken the sites down :-/

**Comment by floere** [comment]
This is definitely a bug - we need to handle all cases.

**Comment by floere** [comment]
@orta What I am saying is that this is an error we need to deal with in cocoapods.org. The metrics API can be down for many reasons, and we need to deal with the case that the metrics API is down correctly.

**Comment by orta** [comment]
I get you, don't worry, I was putting in some extra data on what was happening
