### ISSUE TITLE
Badly Documented

### ISSUE THREAD

**Issue by krzyzanowskim** [CocoaPods/cocoapods.org#238]
Hi,

Something changed, but this is not really documented. I realized that one of my projects went from "great documented" to "badly documented" badge without any significant change to the docs. Would you elaborate a bit how this badge is calculated ?

**Comment by orta** [comment]
Documentation is gathered by Jazzy by looking at all publicly accessible selectors/classes etc, we then use that as documented in: https://guides.cocoapods.org/making/quality-indexes.html

**Comment by orta** [comment]
It's likely that jazzy crashed if you went from something to nothing, I keep up to date with all public jazzy releases but it's got a lot of work to do, you can help them out by testing it with your library.
