### ISSUE TITLE
Inconsistent pod quality ratings. Library gets "Great README" *and* "Empty README"

### ISSUE THREAD

**Issue by jessesquires** [CocoaPods/cocoapods.org#242]
Discovered this from @orta's [tweet](https://twitter.com/orta/status/679718709523513344).

The following libraries have both `Great README` and `Empty README` ratings:

* [JSQCoreDataKit](https://cocoapods.org/pods/JSQCoreDataKit/quality)
* [JSQSystemSoundPlayer](https://cocoapods.org/pods/JSQSystemSoundPlayer/quality)
* [JSQNotificationObserverKit](https://cocoapods.org/pods/JSQNotificationObserverKit/quality)

Further, [JSQDataSourcesKit](https://cocoapods.org/pods/JSQDataSourcesKit/quality) has `Empty README` even though that is [not the case](https://github.com/jessesquires/JSQDataSourcesKit/blob/develop/README.md).

CocoaPods Y U NO :cry:

**Comment by danthorpe** [comment]
Hi, not that I wish to spark a *me too* avalanche, but just wanted to say that this might well be widespread - certainly not just @jessesquires pods. I lost a quality slice of 🧀 with the latest version of [Operation](https://cocoapods.org/pods/Operations/quality).

**Comment by orta** [comment]
It's alright, it affected _every_ pod with a README ( not using documentation_url ) looks like I've got a fix

**Comment by orta** [comment]
Alright, set off a batch job re-parsing, should see everything fixed in the next ~10m

<img width="609" alt="screen shot 2015-12-24 at 19 10 03" src="https://cloud.githubusercontent.com/assets/49038/11997376/fc4b636a-aa71-11e5-90b4-65f4a66bd6d1.png">

**Comment by danthorpe** [comment]
Great stuff @orta! Really like the recent changes with the quality indexes too.

**Comment by orta** [comment]
Thanks @danthorpe - there's been some investing talk internally about how we can improve the numerical values but I think they're a great way to offer positive incentives 

Looks like JSQStuff is in here, so I'm closing this

<img width="1280" alt="screen shot 2015-12-24 at 19 18 24" src="https://cloud.githubusercontent.com/assets/49038/11997436/1ec2b8b6-aa73-11e5-9620-51f62ea37952.png">

**Comment by jessesquires** [comment]
Thanks @orta! :tada:
