### ISSUE TITLE
Duplicate Search Results

### ISSUE THREAD

**Issue by mgroger2** [CocoaPods/cocoapods.org#248]
I just created a new pod and, when searching for it, I found duplicate search results.

I found several issues related to this issue, but they seemed to all be closed.
Most recently: [Issue #231](https://github.com/CocoaPods/cocoapods.org/issues/231), which was closed as a duplicate of [Issue #226](https://github.com/CocoaPods/cocoapods.org/issues/226), which referenced [Issue #97 (on search.cocoapods.org)](https://github.com/CocoaPods/search.cocoapods.org/issues/97). 
Issue 97 doesn't seem to provide any resolution to this issue. It suggests that perhaps this problem will go away of its own accord after some time.

<img width="824" alt="screen shot 2016-01-13 at 11 32 40 am" src="https://cloud.githubusercontent.com/assets/10341071/12300787/0614e82a-b9eb-11e5-91a4-8dbdc034e3b1.png">

**Comment by floere** [comment]
@mgroger2 What a nice issue entry. Thanks for researching and collecting relevant issues.

Thanks to you noting down the time you've given me a crucial hint – that the issue may be related to Heroku restarting the search engine dynos.

**Comment by michalkonturek** [comment]
Same here. I deployed the pod and it is duplicated in the search results.

![screen shot 2016-08-22 at 11 54 08](https://cloud.githubusercontent.com/assets/288030/17857735/d7f5b07a-687a-11e6-9a71-aa2fb8b592fe.png)
 
I would like to also point out that the pod, despite being listed here:

![screen shot 2016-08-22 at 11 28 57](https://cloud.githubusercontent.com/assets/288030/17857933/a7f69744-687b-11e6-9e17-8f75bfd042ec.png)

was never mentioned in [@CocoaPodsFeed](https://twitter.com/cocoapodsfeed)

Also, there is no *Expand* section and link re-directs to GitHub - issue #282

**Comment by orta** [comment]
I've given this another attempt client side - https://github.com/CocoaPods/cocoapods.org/pull/289

**Comment by danielpassos** [comment]
Hey @orta,

I'm with the same problem with one of my library. 

<img width="1440" alt="screenshot 2017-10-27 09 54 53" src="https://user-images.githubusercontent.com/13337/32102899-03f3b7aa-bafd-11e7-9357-bb031e09f8c4.png">
