### ISSUE TITLE
Version numbers are wrong on Installation guide.

### ISSUE THREAD

**Issue by 14lox** [CocoaPods/cocoapods.org#253]
<img width="629" alt="screen shot 2016-02-18 at 11 45 33 am" src="https://cloud.githubusercontent.com/assets/1490398/13130135/eb19e8ba-d635-11e5-8c1b-f1d942a8f6b5.png">
https://github.com/coinbase/coinbase-ios-sdk is currently `3.2.2` but Installation guide shows `3.2`

**Comment by orta** [comment]
This is correct, this will allow for minor updates but not major.

On my phone, replies will be curt.

**Comment by 14lox** [comment]
Ah OK. Carry on.
