### ISSUE TITLE
Cocoapod not updated as deprecated

### ISSUE THREAD

**Issue by hkellaway** [CocoaPods/cocoapods.org#254]
I submitted a new podspec to the master repo for a pod that marked it as `deprecated` - this was done 2 weeks ago. Despite that, the pod is still reflected as not deprecated and i do not see the deprecated version listed in the master repo.

Here at the specs for the pod: https://github.com/CocoaPods/Specs/tree/5e07088fac755758513e8533b934b779361fc3b1/Specs/HNKServerFacade
 
It does not include a new spec `0.3.0-deprecated` that was made prior. When I tried to resubmit that spec however, thinking I had maybe forgot to submit it, I received the message `Unable to accept duplicate entry for: HNKServerFacade (0.3.0-deprecated)`. :confounded:

**Comment by orta** [comment]
So this is an interesting one, what you've ended up doing is making a pre-release version of `0.3.0` when you added the `deprecated` flag, so order-wise it becomes 

<img width="238" alt="screen shot 2016-02-20 at 10 38 47" src="https://cloud.githubusercontent.com/assets/49038/13197522/237516a6-d7be-11e5-9e20-f3cc1f1fec38.png">

so the latest build `0.3.0` isn't classed as deprecated, and we resolve to that as it's the latest build.  If you use CocoaPods 1.0 you can use `pod trunk deprecate` to fix it automatically.

**Comment by hkellaway** [comment]
ah - that makes sense! thank you

**Comment by orta** [comment]
No problem!
