### ISSUE TITLE
Outdated? Link to CocoaPods.app

### ISSUE THREAD

**Issue by ZaneH** [CocoaPods/cocoapods.org#259]
Rather than bringing harm to the project due to my lack of Ruby knowledge, I decided opening an issue would be better.

The download link on https://cocoapods.org/app is returning 404, and I assume this is because the `cocoapods-core` version and the `cocoapods-app` release revision are different (1.0.0.beta.3 & 1.0.0.beta.5 respectively).

Now, if my Ruby detective skills are where they should be, the answer is as simple as changing line 4 at [Core/gem_version.rb](https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/gem_version.rb#L4) to make line 3 at [cocoapods.org/app.slim](https://github.com/CocoaPods/cocoapods.org/blob/master/views/app.slim#L3) valid.

**Comment by segiddins** [comment]
The real solution is to release a new beta of the app

**Comment by orta** [comment]
Aye, it is, and I have :+1:
