### ISSUE TITLE
Search doesn't work ... in my country.

### ISSUE THREAD

**Issue by x1024** [CocoaPods/cocoapods.org#262]
The search on the site completely doesn't work.

I am testing with: https://cocoapods.org/?q=test
(tested with both HTTP and HTTPS, on Chrome & Firefox)

The list of results never populates, because of a failed API call.

The error message is:
**XMLHttpRequest cannot load https://search.cocoapods.org/api/v1/pods.picky.hash.json?query=test&ids=20&offset=0&sort=quality. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://cocoapods.org' is therefore not allowed access. The response had HTTP status code 403**

Opening the site via http://geopeeker.com works properly. Opening it via a tunnelling solution like TunnelBear also works.
I'm guessing this is a CDN issue where the appropriate headers are stripped.

**Comment by orta** [comment]
Interesting, as we don't see this locally - can you submit a PR to https://github.com/CocoaPods/search.cocoapods.org

**Comment by floere** [comment]
Hi x x!

Thanks for the issue.
No need to open a PR (pretty sure @orta meant issue, not PR) on search.cocoapods.org, as this issue is likely as relevant there as it is here. We'll investigate and get back to you if and when we have more information.

**Comment by atulvuliv** [comment]
Please fix this issue. I can't search anything on cocoapods.org

**Comment by floere** [comment]
@atulvuliv Note that you can always use `pod search` on the command line.

**Comment by NinoScript** [comment]
I'm having this same error from Chile, and I have confirmation that the search isn't working either for people in the US, so it doesn't seem to be a country thing.

**Comment by orta** [comment]
This issue was time sensitive, and doesn't need to still be open.
