### ISSUE TITLE
Paragraph missing from Pod description (Lookback/LookbackSafe)

### ISSUE THREAD

**Issue by bgerstle** [CocoaPods/cocoapods.org#279]
## Overview
There's a paragraph before the last sentence in our description which is missing from both "variants" of our Pod (regular and "Safe").  The spec looks like this:

``` ruby
Pod::Spec.new do |s|
  s.name = "LookbackSafe"
  s.description = <<-DESCRIPTION
Lookback is a tool and library for user experience testing
that you can integrate into your app. Lookback records the
iOS screen, the front-facing camera, microphone, metadata,
touches and active views, and uploads it all in
near-realtime to lookback.io where you can study and dive
into the data. Example use cases:

* User testing sessions. Instead of mounting web cams in your
testing lab to record both the screen and your tester's
reactions, let Lookback do the hard work for you.
* Long-term usability study. Let a user record a week of
using your app, and study trends, reactions and recurring
problems.
* Quality assurance. Record videos of found bugs, complete
with a trace of how the tester reached it.

This version of Lookback is safe to use on the Apple AppStore,
but this safety has heavy performance penalties. If you just
want to use Lookback for video bug reports and similar
internally while developing your app, consider using
Lookback HD (the "Lookback" pod).

See some more examples over at http://lookback.io/examples.
DESCRIPTION
  # ...
end
```

## Expected results
The paragraph "This version of Lookback is safe..." appears before the "See some more examples..." closing sentence.

## Actual results
Paragraph before closing sentence is not shown on cocoapods.org:

- https://cocoapods.org/pods/LookbackSafe
- https://cocoapods.org/pods/Lookback (same here, should have a paragraph starting with "Use this version...")

You can see the text is present in the [JSON spec](https://github.com/CocoaPods/Specs/blob/e4d5f0aa9faa99efa24bd2e498a80fa7e3829562/Specs/Lookback/1.3.0/Lookback.podspec.json#L5) but I'm guessing there's a heuristic that's causing it to be stripped from the rendered HTML.

**Comment by orta** [comment]
The text on the CocoaPods webpage is your README rendered as HTML, the description isn't really used too much on the web website - it's more for `pod search` if I recall. ( Or for CocoaDocs to fall back on if there's no README for example )

**Comment by bgerstle** [comment]
Ah, I see. Thanks for clarifying that!
