### ISSUE TITLE
Cocoapod page redirecting to github

### ISSUE THREAD

**Issue by xtrinch** [CocoaPods/cocoapods.org#282]
I made a new pod and pushed it to trunk. It's appearing in the cocoadocs (http://cocoadocs.org/docsets/KeyboardLayoutHelper/0.0.1/) page, but http://cocoapods.org/pods/KeyboardLayoutHelper is redirecting to github.

The pod is working as expected when installed with pod install.

It's been about two days since I published it, I thought initially that maybe it takes a while for the page to appear, but now I'm not so sure anymore.

Did I do something wrong or is this an issue with te webpage?

**Comment by ryot** [comment]
It's a reoccurrence of #https://github.com/CocoaPods/cocoapods.org/issues/155

**Comment by michalkonturek** [comment]
@xtrinch and there is no **Expand** section generated. I am having having the same problem with the pod I deployed, in addition to #248

**Comment by orta** [comment]
all of these are now working, I followed the instructions in the [issue template](https://github.com/CocoaPods/cocoadocs.org/blob/master/.github/ISSUE_TEMPLATE.md) and requested a redeploy 

http://cocoapods.org/pods/KeyboardLayoutHelper
http://cocoapods.org/pods/AreaMetricsSDK
http://cocoapods.org/pods/ScreenBrightness

**Comment by michalkonturek** [comment]
Thanks for sorting that out @orta 

Unfortunately the pod is not listed under my profile: https://cocoapods.org/owners/1132

**Comment by paulb777** [comment]
After pod trunk push, https://cocoapods.org/pods/DigitsMigrationHelper is redirecting to the s.homepage in its podspec instead of going to a CocoaPods page.
