### ISSUE TITLE
Inconsistent Quality Indexes of Tests

### ISSUE THREAD

**Issue by JustinJiaDev** [CocoaPods/cocoapods.org#287]
My project: https://github.com/TintPoint/Overlay
Environment: Xcode 8 / Swift 3 / XCTest

My project contains valid tests. However, the [quality indexes](https://cocoapods.org/pods/Overlay) shows that my project does not have any test.

<img width="937" alt="screen shot 2016-08-30 at 4 43 02 pm" src="https://cloud.githubusercontent.com/assets/3337361/18082314/dd412990-6ed0-11e6-8c3c-5861c36255da.png">

My project has a test target with valid product type:

```
productType = "com.apple.product-type.bundle.unit-test";
```

It contains valid test files that have valid `XCTAssert`s.

Related code: https://github.com/CocoaPods/cocoadocs.org/blob/d78bf7a01adfba29b6a0d4c3a119b701a6510c22/classes/testing_idealist.rb

Related Issue: https://github.com/CocoaPods/cocoadocs.org/issues/440

But I didn't do anything magical to my project file.

**Comment by orta** [comment]
Looks like an Xcode 8 issue, will need to re-parse this once Xcode 8 is supported on CocoaDocs:

```
RuntimeError: [Xcodeproj] Unknown object version.
from /Users/orta/.gem/ruby/2.1.3/gems/xcodeproj-1.2.0/lib/xcodeproj/project.rb:217:in `initialize_from_file'
```

**Comment by JustinJiaDev** [comment]
This is fixed.
