### ISSUE TITLE
Pod’s page should be pinned its latest stable release version

### ISSUE THREAD

**Issue by friedbunny** [CocoaPods/cocoapods.org#288]
When testing out whether or not to publish pre-release builds to CocoaPods (https://github.com/mapbox/mapbox-gl-native/issues/6235), I noticed that [cocoapods.org](https://cocoapods.org/pods/Mapbox-iOS-SDK) immediately switched to showing the new, pre-release version — 3.4.0-alpha.3, in this case.

CocoaPods (the tool) doesn’t upgrade developers to pre-release pods unless they explicitly specify such a version and **I expected the website to continue showing the latest stable release version, too**.

We at Mapbox don’t want the average developer to use pre-releases. We’d like to be able to publish pre-release versions to CocoaPods for testers, but this is currently blocking us from doing that.

![screen shot 2016-09-01 at 4 12 32 pm](https://cloud.githubusercontent.com/assets/1198851/18183190/3b12c36c-7061-11e6-8090-b046bd027cbf.png)

I’ve since deleted the 3.4.0-alpha.3 from CocoaPods trunk and [the page](https://cocoapods.org/pods/Mapbox-iOS-SDK) is back to the latest stable release.

**Comment by orta** [comment]
We do this ( http://blog.cocoapods.org/Release-Versions-Only/ ) - I think that CocoaPods is not considering your version a SemVer version, which should be improved in the next CP release - https://github.com/CocoaPods/Core/pull/350

**Comment by codytwinton** [comment]
@friedbunny @orta - I'm not sure if this is a regression, but I'm running into a similar issue with the latest version of the website.

![screen shot 2019-02-14 at 10 21 58 am](https://user-images.githubusercontent.com/4325900/52808357-880c6800-3042-11e9-8e3f-e45edba89816.png)

**Comment by friedbunny** [comment]
@codytwinton As far as I’m aware, this was never fixed. Mapbox _does_ currently push pre-releases to trunk, as we eventually decided that being able specify pre-releases in podfiles was more important than the CocoaPods website being a bit reckless with versioning. 😉

**Comment by codytwinton** [comment]
well. damn. rip.
