### ISSUE TITLE
Podspec links are broken after sharding

### ISSUE THREAD

**Issue by alexsorokoletov** [CocoaPods/cocoapods.org#303]
Pod page on CocoaPods.org has link to podspec. 
The links are broken after [sharding](http://blog.cocoapods.org/Sharding/) change

For example, https://cocoapods.org/pods/AWSCognito links to https://github.com/CocoaPods/Specs/blob/master/Specs/AWSCognito/2.4.12/AWSCognito.podspec.json which gives HTTP 404.

**Comment by orta** [comment]
Fixed by https://github.com/CocoaPods/cocoapods.org/issues/304
