### ISSUE TITLE
Download Statistics don't appear to be updating

### ISSUE THREAD

**Issue by miller-ms** [CocoaPods/cocoapods.org#306]
Download metrics don't appear to be calculating correctly any longer.  Downloads this week has been the same value for weeks now for all of my pods while total remains the same.  I would expect if the total isn't changing then downloads this week should be showing zero after one week of no downloads and zero for the month after 4 weeks of no downloads.

**Comment by segiddins** [comment]
Please see https://github.com/CocoaPods/metrics.cocoapods.org/issues/43.
