### ISSUE TITLE
Owner view is missing recently created pods

### ISSUE THREAD

**Issue by marmelroy** [CocoaPods/cocoapods.org#307]
This seems to be an issue for pods created after the repo's sharding. 

For example, see Katana's pod:
https://cocoapods.org/pods/Katana

The listing says it was created by Bending Spoons but when accessing Bending Spoon's owner view it says they have 0 pods. https://cocoapods.org/owners/16937

I have checked with a few other recently created pods and can confirm this issue exists for all of them.

**Comment by orta** [comment]
Ouch, wonder what's making that fail

**Comment by marmelroy** [comment]
¯\_(ツ)_/¯

**Comment by marmelroy** [comment]
Looks like it's magically fixed...
