### ISSUE TITLE
Search result missing "Expand" for pod

### ISSUE THREAD

**Issue by amadkhilji** [CocoaPods/cocoapods.org#308]
Hi,
I'm facing the issue with my pod `GoogleMobileAdsMediationUnity`. I can't expand it in [cocoapods.org](https://cocoapods.org) search. I'm seeing `Site`, `Docs`, and `Spec` instead of `Expand`. And when I click [GoogleMobileAdsMediationUnity](https://cocoapods.org/pods/GoogleMobileAdsMediationUnity), it takes me to the homepage. However my other pods are working fine.

Thanks!
Google AdMob Mediation Team.

**Comment by orta** [comment]
Hi there, as the [issue template](https://github.com/CocoaPods/cocoapods.org/blob/master/.github/ISSUE_TEMPLATE.md#is-this-issue-about-your-individual-cocoapods-page-on-the-website) mentions, this is not the place to raise issues about that - the CocoaDocs repo shows you how to help diagnose this yourself. 

However, while writing this I triggered the re-parse and its all working now - http://cocoapods.org/pods/GoogleMobileAdsMediationUnity 👍

**Comment by amadkhilji** [comment]
Thanks orta.
