### ISSUE TITLE
Pre-release pod in not correctly shown in the website

### ISSUE THREAD

**Issue by MP0w** [CocoaPods/cocoapods.org#309]
hi, I pushed a pre-release version of a pod yesterday and I think something broke.
http://cocoapods.org/pods/Matrioska Redirects to github, is not searchable in cocoapods.org or cocoadocs (but docs were generated, BTW I noticed this bug because the doc coverage badge says invalid)

**Comment by orta** [comment]
We only show release versions: http://blog.cocoapods.org/Release-Versions-Only/
