### ISSUE TITLE
New pod not generating page on CocoaPods.org (RuAWSS3)

### ISSUE THREAD

**Issue by brunomacabeusbr** [CocoaPods/cocoapods.org#313]
I pushed a new pod recently (RuAWSS3) and its pod page isn't showing up on CocoaPods.org.
And, the [pod's url](http://cocoapods.org/pods/RuAWSS3) redirect to [pod's GitHub page](https://github.com/brunomacabeusbr/RuAWSS3).

**Comment by orta** [comment]
Hi there, as the [issue template requests](https://github.com/CocoaPods/cocoapods.org/blob/master/.github/ISSUE_TEMPLATE.md) - please consult the CocoaDocs repo about how to debug this.

**Comment by brunomacabeusbr** [comment]
Sorry.
I'm going here [because this SO question](http://stackoverflow.com/questions/38154360/cocoapods-page-redirecting-to-github) =P
