### ISSUE TITLE
Using branch instead of tag when deploying pod breaks trunk docs.

### ISSUE THREAD

**Issue by jugutier** [CocoaPods/cocoapods.org#315]
Moved from https://github.com/CocoaPods/CocoaPods/issues/6443 

# Report

## What did you do?

ℹ  When uploading my own pod I used `pod trunk push` but with a branch `0.0.1` instead of a tag. Both the lint before and the push succeeded but cocoapods.org never listed my README as part of the docs.

## What did you expect to happen?

ℹ To either not allow me to use a branch instead of a tag or list the documentation correctly.

## What happened instead?

ℹ My pod was listed in cocoapods.org but broken link and wouldn't expand the docs.

I waited five days and still wouldn't so I redeployed using a tag. The error is not visible with my pod anymore.

## CocoaPods Environment

ℹ 
### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5bf4bfa37afff74e64cbc1003172865620faf9d7
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

**Comment by orta** [comment]
This will probably be fixed due to http://blog.cocoapods.org/CocoaPods-Metadata-Service/
