### ISSUE TITLE
Web search returns 503

### ISSUE THREAD

**Issue by Nebary** [CocoaPods/cocoapods.org#319]
When requesting `https://cocoapods.org/?q=crop` in Chrome

I receive 503. Here is more details:
> Request URL:https://search.cocoapods.org/api/v1/pods.picky.hash.json?query=crop&ids=20&offset=0&sort=quality
> Request Method:GET
> Status Code:503 
> Remote Address:104.18.60.114:443

Response Header:
> cache-control:no-cache, no-store
> cf-ray:343ccfb249d7587f-DFW
> content-type:text/html; charset=utf-8
> date:Wed, 22 Mar 2017 23:08:40 GMT
> server:cloudflare-nginx
> set-cookie:__cfduid=db41d61326f65a083a94342db3bf73e7d1490224089; expires=Thu, 22-Mar-18 23:08:09 GMT; path=/; domain=.cocoapods.org; HttpOnly
> status: **503**

Request Headers:
> :authority:search.cocoapods.org
> :method:GET
> :path:/api/v1/pods.picky.hash.json?query=crop&ids=20&offset=0&sort=quality
> :scheme:https
> accept:application/json, text/javascript, */*; q=0.01
> accept-encoding:gzip, deflate, sdch, br
> accept-language:en-US,en;q=0.8
> origin:https://cocoapods.org
> referer:https://cocoapods.org/?q=crop
> user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

Response Body:
```
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<title>Application Error</title>
<style media="screen">html,body,iframe{margin:0;padding:0;}html,body{height:100%;overflow:hidden;}iframe{width:100%;height:100%;border:0;}</style>
</head>
<body>
<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
</body>
</html>
```

**Comment by Nebary** [comment]
Here is Charles HAR session file for more details
[cocoapods.org.har.zip](https://github.com/CocoaPods/cocoapods.org/files/863179/cocoapods.org.har.zip)

**Comment by segiddins** [comment]
We appear to be running out of memory on search

**Comment by Nebary** [comment]
Got it @segiddins

**Comment by orta** [comment]
Closing as we moved search to AWS which is more stable
