### ISSUE TITLE
[question] In-house cocoapods.org for private pods

### ISSUE THREAD

**Issue by mgrebenets** [CocoaPods/cocoapods.org#320]
This is rather a question or a feature request.

Is it possible to host my own version of `cocoapods.org` for internal pods?
We have private pods repo configured and are looking into better ways to make our internal pods discoverable.

Having something like `mycompany-cocoapods.com.au` would be incredibly helpful.

So obviously that would raise tons of questions:

- How to "point" this repo to internal pods?
- What are the required changes in terms of postgres DB, documentations links, etc, etc.
- Is it even possible?

**Comment by orta** [comment]
This isn't really possible without a very very considerable amount of
effort I'm afraid, the site is really the front end for multiple services
you'd need to get running

E.g cocoadocs, search.cocoapods, trunk.cocoapods, metrics.cocoapods,
cocoadocs-api.cocoapods

The closest to useful IMO is trying to run your own cocoadocs, it'd require
some code changes in there but it's feasible

**Comment by mgrebenets** [comment]
Thanks @orta 👍 
I suspected that would be the case after stumbling upon issues with `rake db:migrate` :)

We don't have thousands frameworks in our case, I guess we could come up with simple static website to browse all our frameworks. Not as feature rich as cocoapods.org, but something that can render basic info from podspecs with links to documentation.

If you know of anything that could help with achieving that goal, I'd appreciate the hint.

Thanks again!
