### ISSUE TITLE
README.md from the git repo is not updated on cocoapods.org

### ISSUE THREAD

**Issue by markpiller** [CocoaPods/cocoapods.org#321]
We published a new version of our pod which you can see at:
https://cocoapods.org/pods/Backendless

The podspec for the version is available at:
https://github.com/CocoaPods/Specs/blob/master/Specs/5/4/4/Backendless/4.0b3/Backendless.podspec.json

The problem is the README.md file from the github repo is not shown on page for our pod - it shows some old/outdated file. 

The file we need to be rendered is at:
https://github.com/Backendless/ios-SDK/blob/master/README.md

**Comment by Fidetro** [comment]
I have same Issue,Did you solve it?

**Comment by markpiller** [comment]
Somehow it just got updated in cocoapods. Although the file is still cached in the Cocoapods side - we change it in github, but the changes are not propagated.

**Comment by zezha-msft** [comment]
I'm having the same issue 😢  

@Fidetro Did your pod fix itself?

**Comment by Fidetro** [comment]
@zezha-msft My pod update README in next version，but I don't know how to fix it

**Comment by paynerc** [comment]
We also have a new `README.md`, but Cocoapods.org is still showing the old version.

**Comment by zezha-msft** [comment]
@Fidetro Ok thank you!

To the admins: could you please trigger the documentation update again for us?

My pod is [here](cocoapods.org/pods/AZSClient).

**Comment by Zyphrax** [comment]
I'm having the same issue: https://cocoapods.org/pods/Telegraph
The README isn't up-to-date.

Is this a bug? Or should I somehow trigger an update?

**Comment by omaralbeik** [comment]
We're having the same problem for https://cocoapods.org/pods/SwifterSwift

**Comment by mayankk2308** [comment]
Same issue with my pod at: https://cocoapods.org/pods/MKDataDetector

**Comment by orta** [comment]
This should probably be fixed by https://github.com/CocoaPods/trunk.cocoapods.org/pull/235 and https://github.com/CocoaPods/cocoadocs.org/pull/555 - you're welcome to run through the help instructions [in the README](https://github.com/CocoaPods/cocoapods.org#getting-help)

**Comment by ronakdev** [comment]
This is happening with me:
https://cocoapods.org/pods/ZestySwiftContentEndpointWrapper
vs
https://github.com/zesty-io/ZestySwiftContentEndpointWrapper

**Comment by Ajaypp242** [comment]
I am facing same issue cocopod document not updating from latest version Read.me

**Comment by jevonmao** [comment]
My Cocoapod shows up on the search results, but it keeps redirecting to Github page. https://cocoapods.org/pods/PermissionsSwiftUI

**Comment by pedro-otoai** [comment]
Facing the same issue here as well. Any solutions?

**Comment by jadebowl** [comment]
Hey there,
I am still facing this issue. Even though the version number is correct on top (latest 3.0.2), the README.md is not updating. 
It's still at the initial version but I had to change the Library name so I really need it to update. Did anyone find a solution for this?

<img width="897" alt="Screenshot 2023-10-12 at 22 31 21" src="https://github.com/CocoaPods/cocoapods.org/assets/57940508/eff5e780-6b59-4646-bce5-58a8b5c9b888">

CocoaPods: https://cocoapods.org/pods/AlertViewCustom
GitHub: https://github.com/jadebowl/AlertViewCustom

**Comment by jevonmao** [comment]
This is by no means official, and just my personal speculation, but for everyone also experiencing this issue still, it is not fixed and likely will never be. With how widely adopted SPM is now, Cocoapods is almost completely obsolete.
