### ISSUE TITLE
Wrong CHANGELOG displayed

### ISSUE THREAD

**Issue by fpillet** [CocoaPods/cocoapods.org#323]
When searching for `NSLogger' on the website, we end up on the correct page. But when clicking the CHANGELOG button, the CHANGELOG for another project (apparently PLCrashReporter) is displayed. The other project is not even mine.

What is this sorcery? :)

**Comment by orta** [comment]
This should probably be fixed by https://github.com/CocoaPods/trunk.cocoapods.org/pull/235 and https://github.com/CocoaPods/cocoadocs.org/pull/555 - you're welcome to run through the help instructions [in the README](https://github.com/CocoaPods/cocoapods.org#getting-help)
