### ISSUE TITLE
Pod link redirecting to website.

### ISSUE THREAD

**Issue by SanjithKanagavel** [CocoaPods/cocoapods.org#334]
I have published SDK two days before. Looks like its visible while you search but its redirecting when you click on search result. And Cocoa Docs is giving 404. Can anyone please help with this ?

**Comment by orta** [comment]
This should probably be fixed by https://github.com/CocoaPods/trunk.cocoapods.org/pull/235 and https://github.com/CocoaPods/cocoadocs.org/pull/555 - you're welcome to run through the help instructions [in the README](https://github.com/CocoaPods/cocoapods.org#getting-help)
