### ISSUE TITLE
Minimum README

### ISSUE THREAD

**Issue by zevarito** [CocoaPods/cocoapods.org#338]
What is the criteria for a Minimal README and how you exactly do you know if the information there is enough or not? Are you applying ML, counting chars, what is the strategy?

I have a README with the following sections:

* TOC
* Versioning
* Features
* Documentation -> a link to it
* Example App -> description plus a link
* Installation -> link
* License

Cocoapods quality metrics report:

- -5 Minimal README
- +8 Has a CHANGELOG
- +4 Has Tests
- +5 Post-1.0.0

**Comment by orta** [comment]
The score is documented in this gem's repos: https://github.com/clayallsopp/readme-score 👍
