### ISSUE TITLE
Overview and CHANGELOG not updated

### ISSUE THREAD

**Issue by hkellaway** [CocoaPods/cocoapods.org#340]
Noticed the `Overview` and `CHANGELOG` sections on my pod listing are out-of-date.

CocoaPods.org: https://cocoapods.org/pods/Gloss
Actual: https://github.com/hkellaway/Gloss/blob/2.0.0-beta.2/README.md

The CHANGELOG halts at version `1.2.4`, whereas the pod is at `2.0.0-beta.2`:

https://github.com/hkellaway/Gloss/blob/2.0.0-beta.2/CHANGELOG.md

I notice it stopped updating these when my pod switched to Swift 4.0.

Perhaps related, the Swift version indicates `3.0` whereas it should be `4.0`

**Comment by orta** [comment]
I fixed this with https://github.com/CocoaPods/trunk.cocoapods.org/pull/235 last night 👍

**Comment by gomezo76** [comment]
Hi, 

7 days ago we updated our SDK, the Changelog is not up to date, it's still the one of the previous version (6.7.1 instead of 6.7.2), what should be done on our side ?

pod: SmartAdServer-DisplaySDK

thks,

Julien
