### ISSUE TITLE
Download counter broken?

### ISSUE THREAD

**Issue by gk-brown** [CocoaPods/cocoapods.org#341]
One of my projects (https://cocoapods.org/pods/MarkupKit) had been consistently seeing 100+ downloads/month for quite a while, and suddenly dropped to 0 within the past couple of weeks. 

While this could certainly represent a lull in activity, I wanted to report it on the off chance that it was due to a bug in the counter.

**Comment by orta** [comment]
Looks like this is happening on all pods - /cc @DanToml

**Comment by gk-brown** [comment]
Any update on this?

**Comment by orta** [comment]
I'm afraid CocoaPods is run on volunteers spare time, so we can only get time to do it when there's free time. We'll update the tickets when something changes 👍

**Comment by gk-brown** [comment]
I am also a volunteer developer, so I completely understand. Just looking forward to seeing this resolved since I find the stats very useful.

**Comment by DanToml** [comment]
This should be up and running again now, I had to provision an extra node for the Redshift cluster.

**Comment by gk-brown** [comment]
Thanks - it does seem to be working again. Do the current numbers reflect the entire period that the service was down, or just since it came back up?

**Comment by DanToml** [comment]
@gk-brown It should be the entire period... depending on the segment retention period. We synced a few hundred million back events though.

**Comment by gk-brown** [comment]
Just wanted to clarify since the numbers seemed low (though not exceptionally so). 

Thanks!
