### ISSUE TITLE
Outdated version of CocoaPods App on website

### ISSUE THREAD

**Issue by Erikmitk** [CocoaPods/cocoapods.org#342]
The [website](https://cocoapods.org/app) shows version 1.1.1 to be the most recent release and offers a direct download link.

After installing I noticed that an update was available for version 1.2.0. Which is now the case since January if you check out the releases page (https://github.com/CocoaPods/CocoaPods-app/releases).

If the app is available for download on the website it should display the most recent version correctly.

**Comment by orta** [comment]
This got updated.
