### ISSUE TITLE
Readme not updated

### ISSUE THREAD

**Issue by niveuseverto** [CocoaPods/cocoapods.org#345]
Greetings.

Yesterday were update of our pod: https://cocoapods.org/pods/VoxImplantSDK

CocoaPods website is still showing old readme.

When I ran CocoaDocs locally - readme was correctly updated.

**Comment by groue** [comment]
Same problem happens to http://cocoapods.org/pods/GRDB.swift (2.4.0 is still showing, when several versions have shipped since then).

Running `curl http://199.19.84.242:4567/redeploy/GRDB.swift/latest` fails with a timeout.

**Comment by VectauryPernic** [comment]
Same Problem https://cocoapods.org/pods/Vectaury

**Comment by groue** [comment]
Same for https://cocoapods.org/pods/RxGRDB as well (0.7.0 still showing, when 0.8.0 and 0.8.1 have shipped since).

**Comment by sisoje** [comment]
No ones pod is working, using this url you can see more info
https://cocoadocs.buddybuild.com/error/PromiseKit

**Comment by VectauryPernic** [comment]
https://cocoadocs.buddybuild.com/error/Vectaury response not found,
what does it mean ?

**Comment by sisoje** [comment]
Vectaury, did you do "pod trunk push" succesfully?

**Comment by sisoje** [comment]
maybe try this: http://cocoadocs.org/docsets/Vectaury/latest

**Comment by VectauryPernic** [comment]
the last version at http://cocoadocs.org/docsets/Vectaury/ are 1.3.3 but current version of cocoa pods are 1.5.1

**Comment by orta** [comment]
These should probably be updated on cocoapods.org for new versions due to http://blog.cocoapods.org/CocoaPods-Metadata-Service/

**Comment by niveuseverto** [comment]
@orta Yesterday pushed update, readme didn't change.

**Comment by groue** [comment]
> These should probably be updated on cocoapods.org

GRDB and RxGRDB still show outdated readmes. @orta, are we supposed to wait? Publish a new version? Or shouldn't this issue be reopened?

**Comment by sisoje** [comment]
currently, documentation on cocoapods.org site is vastly outdated for significant amount of time. maybe get rid of it completely...

also, the links i provided do not work anymore... something is going on behind the scenes but i can not follow what...

**Comment by niveuseverto** [comment]
@orta Any updates on this issue?

**Comment by RiftValleySoftware** [comment]
Hey folks, this now seems to be happening to me again. The redeploy temp script seems to be living up to its potential (temporary). It did work, when this happened last year.

One thing that changed for me, was that I switched my pod (RVS_Spinner) from one owner to another. Maybe that hosed it, as the new owner shows zero pods.

**Comment by iDevelopper** [comment]
It appears that there are many problems currently with Cocoapods. I published a version of the pod PBRevealViewController yesterday and in the result of the search, the description is: "Unparsable at trunk import time."

Also, when I visit my page, two pods appear only instead of three and I have never had an answer for this problem.

**Comment by iDevelopper** [comment]
https://github.com/CocoaPods/cocoapods.org/issues/402#issuecomment-451735520
