### ISSUE TITLE
New pod not generating page on CocoaPods.org 

### ISSUE THREAD

**Issue by cristiLupu** [CocoaPods/cocoapods.org#347]
I pushed a new pod recently, name: **CLWaterWaveView**, and its pod page isn't showing up on CocoaPods.org. 

#### Links
[GitHub Project](https://github.com/cristiLupu/CLWaterWaveView)
[Pod Spec](https://github.com/cristiLupu/CLWaterWaveView/blob/master/CLWaterWaveView.podspec)

#### Things what does't work
* pod page isn't showing up on CocoaPods.org
* search on CocoaPods.org does not find my pod

#### Other Info
CocoaPodsFeeds [tweeted](https://twitter.com/CocoaPodsFeed/status/960194598365794305) the new pod

**Comment by cristiLupu** [comment]
#### Update

Search on CocoaPods.org find my pod, but redirects to GitHub repository.

**Comment by SanjoDeundiak** [comment]
Same here https://github.com/CocoaPods/cocoapods.org/issues/346

**Comment by sisoje** [comment]
I have similar problems.
Something is terribly wrong. I wasted two weeks on this strange behavior, here, see this link for more info:
https://cocoadocs.buddybuild.com/error/CLWaterWaveView

but ofcorse, podspec is totally valid

**Comment by sisoje** [comment]
Every pod is broken. not only new ones, and nobody here to help. 

For example:
https://cocoadocs.buddybuild.com/error/Alamofire
https://cocoadocs.buddybuild.com/error/PromiseKit

Redeploy helped before, but not anymore since ips are outdated...

**Comment by orta** [comment]
These should probably be updated on cocoapods.org for new versions due to http://blog.cocoapods.org/CocoaPods-Metadata-Service/
