### ISSUE TITLE
Download counter broken?

### ISSUE THREAD

**Issue by gk-brown** [CocoaPods/cocoapods.org#348]
The download count for one of my projects (https://cocoapods.org/pods/MarkupKit) has dropped to 0 within the past couple of weeks. I reported a [similar issue](https://github.com/CocoaPods/cocoapods.org/issues/341) back in November.

As I mentioned in the previous issue, this could simply represent a lull in activity. However, I wanted to make sure you were aware of it in case it is due to a problem with the counter.

**Comment by sisoje** [comment]
everything is broken

**Comment by gk-brown** [comment]
Actually, I thought it might have been fixed. The counter seems to be working again.

**Comment by sisoje** [comment]
seems like counter started working for me also, but readme does not update on the cocoapods site

**Comment by gk-brown** [comment]
OK. I haven't tried to push an update recently, so I haven't run into that issue. I have noticed that the "star" count hasn't been updated in months, though.

**Comment by gk-brown** [comment]
Looks like it is broken again...

**Comment by sisoje** [comment]
yes, seems they are tuning it :)

**Comment by gregbrownlumira** [comment]
This still appears to be broken. It seems to work for a short time, then dies again.

**Comment by gk-brown** [comment]
This still appears to be broken. It seems to work for a short time, then dies again.

**Comment by lucdion** [comment]
Download statistics haven't been updated for more than a month. This feature is a really appreciated by developers, it helps to determine if cocoapods are highly used.

**Comment by omaralbeik** [comment]
Still appears to be broken 😭

**Comment by DrBeta** [comment]
@orta Please close this issue

**Comment by orta** [comment]
Ah yeah, I removed these from the front-end
