### ISSUE TITLE
Cocoapods.com pod page redirects to homepage

### ISSUE THREAD

**Issue by adriantofan** [CocoaPods/cocoapods.org#350]
Hello, 

I have issue with one of our pods. When searching on cocoapods.org and/or going directly to our pod page for `FollowAnalytics ` the user is redirected to the homepage specified in the podspec. 

```
$ curl -I https://cocoapods.org/pods/FollowAnalytics
HTTP/2 303
date: Mon, 05 Mar 2018 10:43:41 GMT
content-type: text/html;charset=utf-8
set-cookie: __cfduid=d6d8dc4cf8db4d0af7c9a25ccd89b9bfa1520246621; expires=Tue, 05-Mar-19 10:43:41 GMT; path=/; domain=.cocoapods.org; HttpOnly
location: http://www.followanalytics.com/
vary: Accept-Encoding
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
via: 1.1 vegur
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 3f6bfba9c83a3c11-CDG
```

Instead of being redirected I should see a page with informations about the pod.

Can you help me debug the problem ?

Thank you

**Comment by orta** [comment]
This'll probably be fixed on your next version update due to http://blog.cocoapods.org/CocoaPods-Metadata-Service/
