### ISSUE TITLE
Search doesn't work with "prevent cross-site tracking" enabled in Safari 11

### ISSUE THREAD

**Issue by benasher44** [CocoaPods/cocoapods.org#353]
Safari 11 has this new setting:

<img width="764" alt="screen shot 2018-03-26 at 9 38 29 am" src="https://user-images.githubusercontent.com/1120429/37919681-77b197b4-30d9-11e8-9aed-4244588d172c.png">

When this is enabled, doing a search results in the following errors in the developer console (un-checking that box fixes it):

<img width="1676" alt="37854719-4ee3e094-2ea9-11e8-92f4-ba5015280b38" src="https://user-images.githubusercontent.com/1120429/37919742-a2a16382-30d9-11e8-89f8-db1cd5378d31.png">

I suspect that setting proper Access-Control-Allow-Origin headers will fix this, but I'm not sure and can't find the Safari 11 documentation around this feature 😢

**Comment by Haroenv** [comment]
I have this setting enabled, and it works with the new search architecture, so I think this is solved.

**Comment by benasher44** [comment]
Hey look at that it does! 🎉 thanks!
