### ISSUE TITLE
Convert Search to Algolia

### ISSUE THREAD

**Issue by orta** [CocoaPods/cocoapods.org#356]
Given the instability of search for the last few months, I think it makes sense to start looking at an alternative engine. Algolia powers most other big OSS projects I know, and IMO it can work for CP too.

To replace it we'd need:

* A running algolia instance
* Something to receive webhooks from trunk and to access the trunk db to pass info into the algolia instance
* An update to the front-end to use algolia's API instead of our own search

I don't have the time to build this, so I'm making this issue to help architect it.

/cc @haroenv for advice and ideas (I can also invite you to the CP slack)

**Comment by Haroenv** [comment]
Would love to help out here! Can you send an invite to the slack (hello@haroen.me)?

**Comment by sushant40** [comment]
Hi, I would like to help out with this - can you send me slack invite?... sushant.40@gmail.com

**Comment by orta** [comment]
We got this happening in #364
