### ISSUE TITLE
Searching results in HTTP 502 and 503

### ISSUE THREAD

**Issue by frankkienl** [CocoaPods/cocoapods.org#357]
Problem:
When searching on cocoapods.org, no results are shown.

Steps to reproduce:
1) Go to cocoapods.org
2) Type some letters

Expected:
Pods that match my search results

Actual result:
No search results

The developer tools (in Google Chrome) show the following error:
`Failed to load https://aws-search.cocoapods.org/api/v1/pods.picky.hash.json?query=json&ids=20&offset=0&sort=quality: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://cocoapods.org' is therefore not allowed access. The response had HTTP status code 504.`

![screen shot 2018-04-24 at 09 59 08](https://user-images.githubusercontent.com/1552295/39173841-2867543a-47a6-11e8-900e-76af987b2701.png)

Tried on 2 different MacBooks, with Chrome and Safari

**Comment by orta** [comment]
Discussion in #356

**Comment by orta** [comment]
This should be fixed by #364
