### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by jugutier** [CocoaPods/cocoapods.org#360]
I have tried searching several pods that I know exists and yet the search results are always empty.

Tried in chrome and in safari.

Example:

https://cocoapods.org/?q=colors

Looking at the network tab in chrome doesn't seem to have any errors for that request.

Happy to help if you point me to the right direction :)

**Comment by jugutier** [comment]
Looks like a known issue. Related to: https://github.com/CocoaPods/CocoaPods/issues/7647
And https://github.com/CocoaPods/cocoapods.org/issues/356

**Comment by orta** [comment]
Thanks, yeah, I'm going to close this as a known dupe
