### ISSUE TITLE
Search API not working

### ISSUE THREAD

**Issue by Kapeli** [CocoaPods/cocoapods.org#368]
The search API (e.g. http://search.cocoapods.org/api/v1/pods.flat.hash.json?query=name:AFNetworking) isn't working anymore.

I think this is due to https://github.com/CocoaPods/cocoapods.org/pull/364. Is there any replacement API I could use within Dash?

**Comment by orta** [comment]
Yeah, you can use https://www.algolia.com/doc/api-reference/api-methods/ with `ec568febb45df0876ab2b266a382af32` as your API key and `WBHHAMHYNM` as the App ID, the index should be called `cocoapods`

The data isn't the same shape, and I'm not 100 if it contains all the same data, but this is the index being worked on in https://github.com/CocoaPods/indexer.cocoapods.org/

**Comment by Kapeli** [comment]
Great. Thanks!
