### ISSUE TITLE
Clicking on a pod found at cocoapods.org redirects to GitHub

### ISSUE THREAD

**Issue by vishaljhanjhri** [CocoaPods/cocoapods.org#389]
Hey guys,

First of all let me thank you for the great work that your are doing! Keep it up!

Yesterday I have submitted a pod by running pod trunk push [NAME.podspec].
Everything went smooth, the docs were automatically created and the pod can be successfully installed by adding it to the Podfile.

What I have noticed is that when I try to click on the link of my pod located at cocoapods.org, I am redirected to the GitHub page of the repository, instead of the usual cocoapods behaviour which is expanding the details for the pod.

My pods name are "**Hippo**" and "**HippoCallClient**"  and you can find it on cocoapods.org here.

Is there something wrong with the way the pod was submitted, or maybe this is a new feature of cocoapods.org? Please let me know if we can solve this one.

Thanks in advance!

Cheers,
Vishal

**Comment by DrBeta** [comment]
When you click on the `Hippo` framework, make sure that you click the __Hippo__ on the left, instead of the __Site__ on the right of the table row. This applies to all frameworks.

**Comment by vishaljhanjhri** [comment]
Hi @DrBeta ,

My above issue is resolved earlier when I change my repo public GitLab to GitHub.

**Comment by DrBeta** [comment]
Ok
