### ISSUE TITLE
CocoaPods rating says "EMPTY README" / "Minimal README" even though it's present in the CocoaPod

### ISSUE THREAD

**Issue by Flawion** [CocoaPods/cocoapods.org#392]
Hi, 

I have a strange problem, my readme is visible at cocoapods.org but in quality tab there is an information about 'Empty README'.

https://cocoapods.org/pods/KOControls
https://cocoapods.org/pods/KOControls/quality

**Comment by Flawion** [comment]
Hi guys Happy new year :) Is there new info about my problem? Can someone just refresh my pod info to fix that...?

**Comment by iDevelopper** [comment]
This is the explanation of the notation but not about your readme.

**Comment by Flawion** [comment]
@iDevelopper What do you mean?
