### ISSUE TITLE
Page is returning Internal Server Error

### ISSUE THREAD

**Issue by daniel-beard** [CocoaPods/cocoapods.org#394]
<img width="800" alt="screen shot 2018-12-19 at 2 01 43 pm" src="https://user-images.githubusercontent.com/2645146/50250769-a9303f80-0396-11e9-9864-96fdd41d449a.png">

**Comment by daniel-beard** [comment]
Tested on several different machines + networks.

**Comment by segiddins** [comment]
Should be fixed as of last night.
