### ISSUE TITLE
The search sections should not display duplicates

### ISSUE THREAD

**Issue by fabiopelosin** [CocoaPods/cocoapods.org#40]
The `PODS WITH SUMMARY` section often displays many of the results included in the  `PODS NAMED` section. This creates noise which doesn’t allow to see easily if there is any pod not matched by the name which might be interesting.

An implementation could be to define an order of importance (the current vertical ordering would do fine) for the various sections and just don’t display a pod if it was already included in a more important section.

**Comment by orta** [comment]
I'm still good with not doing this.
