### ISSUE TITLE
New pod not found after publishing 12 hours ago.

### ISSUE THREAD

**Issue by iDevelopper** [CocoaPods/cocoapods.org#402]
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

 pod spec lint PBPopupController.podspec
 pod trunk push PBPopupController.podspec

## RESULT:
Updating spec repo `master`

CocoaPods 1.6.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.6.0.beta.2

Validating podspec
 -> PBPopupController (0.1.2)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file. (in target 'App')

Updating spec repo `master`

CocoaPods 1.6.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.6.0.beta.2

--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  PBPopupController (0.1.2) successfully published
 📅  December 29th, 17:14
 🌎  https://cocoapods.org/pods/PBPopupController
 👍  Tell your friends!

## What did you expect to happen?
Find my pod when I search it, the first version have been pushed this morning 12 hours ago!

## What happened instead?
Not found.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin16]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14.3 (18D32a)
       Xcode : 10.1 (10B61)
         Git : git version 2.4.5
Ruby lib dir : /Users/patrickbodet/.rbenv/versions/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1064200b761a3a19139ae93f6f4f94901e4ad0f0
               RWPodSpecs - https://github.com/iDevelopper/RWPodSpecs.git @ f504174c594fef57e23e66346c00574f4f3fa7e9
```

### Installation Source

```
Executable Path: /Users/patrickbodet/.rbenv/versions/2.2.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by iDevelopper** [comment]
Hey there,

Any news on this?

**Comment by Flawion** [comment]
Hi iDeveloper, you said something about the notation in my topic (https://github.com/CocoaPods/cocoapods.org/issues/392), can you explain what you meant? And how i can fix that problem. Sorry for the offtopic but i wait 2 months for the solution :)

**Comment by iDevelopper** [comment]
Hi @Flawion , it was a mistake. As you can see, I have also some problems and the members do not seems to have a look.

**Comment by iDevelopper** [comment]
Ping...
