### ISSUE TITLE
"Internal Server Error" on pod page

### ISSUE THREAD

**Issue by jonathantribouharet** [CocoaPods/cocoapods.org#403]
Hi,
I have a message "Internal Server Error" on the page of a pod:
https://cocoapods.org/pods/WeProovSDK

I have this error since when I tried to push the gem which give me an error:
https://github.com/CocoaPods/CocoaPods/issues/8405

**Comment by segiddins** [comment]
Seems to be back up now.

**Comment by jonathantribouharet** [comment]
Yes probably because I released a new version of the pod, but I think you still need to check the origin of the bug.

**Comment by Tolik7** [comment]
Guys, I see "Internal Server Error" error AND  I CANT PERFROM pod 'GoogleWebRTC'! PLEASE HELP!
