### ISSUE TITLE
pods page is returning internal server error

### ISSUE THREAD

**Issue by anand-plivo** [CocoaPods/cocoapods.org#404]
We released a new version v2.1.0 and pod page started to show internal server error.
https://cocoapods.org/pods/PlivoVoiceKit 

![screenshot 2019-01-10 at 4 14 33 pm](https://user-images.githubusercontent.com/40763360/50963530-fcf3fb80-14f2-11e9-9389-e69b274295ec.png)

**Comment by orta** [comment]
I'm not seeing this, I just tested locally
