### ISSUE TITLE
Pod Quality score shows penalty for empty README even though there is READMY with ScoreMe score 95, no bonus for Swift code and zero stars even though there are 19.

### ISSUE THREAD

**Issue by RastislavMirek** [CocoaPods/cocoapods.org#409]
I have found that most of recently released pods have incorrect quality score. As an example, [this pod, FlexColorPicker](https://cocoapods.org/pods/FlexColorPicker) has [quality score of 50](https://cocoapods.org/pods/FlexColorPicker/quality) (because of penalty for minimal README and empty README).

However there is a README with [ScoreMe](http://clayallsopp.github.io/readme-score/) (same thing you use to score README) score of 95. There should also be bonus for Swift code, the pod is in Swift 4.2 but there is none. Also your website shows 0 GitHub stars while the library [has 19](https://github.com/RastislavMirek/FlexColorPicker) (and more than zero for over 10 months). 

All together, quality score of the pod should be 73, not 50. That is a big difference. 

Please fix this as it means that quality pods do not show in search while low quality pods do.

**Comment by orta** [comment]
I'm not sure how you found the links to the quality scores (they're not on the website anymore) but they've not been used in search in a year or two, I've just not taken down the routes. So don't worry, it's not used anywhere.

**Comment by RastislavMirek** [comment]
@orta 

1. What is used to rank pods in search then? My pod is not even shown for term "color picker" which is part of its name and in the describtion while obviously lower quality pods are shown for that term (less stars, old, objective-c, small README). 

2. Links for quality score are [on this page](https://cocoapods.org/owners/32204), which is publicly available by clicking pod author name. The page itself also shows quality score.

3. What about incorrect stars, forks, issues count? That is on [main pod page](https://cocoapods.org/pods/FlexColorPicker) and [obviosly incorrect](https://github.com/RastislavMirek/FlexColorPicker).
