### ISSUE TITLE
List supported Xcode versions on web page

### ISSUE THREAD

**Issue by fulldecent** [CocoaPods/cocoapods.org#412]
The CocoaPods project supports various versions of Xcode. And this version support is rolled in at some point, possibly not identical to Apple's release schedule. Please identify exactly which versions of Xcode are supported at these locations:

* https://cocoapods.org
* https://github.com/CocoaPods/CocoaPods/blob/master/README.md

**Comment by fulldecent** [comment]
Thank you. I can do this if you can tell me on good authority which versions of Xcode are currently supported by CocoaPods.

**Comment by orta** [comment]
We aim to support the current production version, and go back one version also. We ship betas of CocoaPods for betas of Xcode's.

I don't think we've ever chosen to drop support for an older Xcode, the xcodeproj format is generally good at backwards compatibility.
