### ISSUE TITLE
Cocoapods Pod page redirects to homepage

### ISSUE THREAD

**Issue by vguerci** [CocoaPods/cocoapods.org#443]
Heya, the issue I'm encountering is basically the same as #331, Creating a new issue as the old one being closed and comments reporting similar errors unseen.
- https://cocoapods.org/pods/CriteoPublisherSdk > issue as it redirects to homepage
- https://cocoapods.org/pods/CriteoEventsSDK > works

**Comment by vguerci** [comment]
So after months, if not years, with that issue, it just got resolved as I noticed after pushing a new version, or maybe someone silently did something... If that is the later, thank for you anonymous help ¯\\\_(ツ)_/¯

**Comment by sha8wn** [comment]
Hello, this still happens to me 
https://cocoapods.org/pods/BYConnect

¯\_(ツ)_/¯

**Comment by yimingc2** [comment]
Hey, guys @vguerci. I have the same issue after successfully uploaded the lib to https://github.com/CocoaPods/Specs
- Can find the pod using `pod search Openpay`
- Can `pod install` the lib
- **Unable** to find it on https://cocoapods.org/ using Search
- https://cocoapods.org/pods/Openpay redirects to the **github home page**

Thanks for looking up for me.

**Comment by sha8wn** [comment]
@yimingc2 - I noticed it takes approximately 24 hours for your pod to show up in the CocoaPods directory.

I can find your pod on the search now: 
![image](https://user-images.githubusercontent.com/1778742/113238897-b5680e80-92ba-11eb-9ce6-7026abbf3bbb.png)

But yes, the redirect issue still happens for you as well.

**Comment by yimingc2** [comment]
> @yimingc2 - I noticed it takes approximately 24 hours for your pod to show up in the CocoaPods directory.
> 
> I can find your pod on the search now:
> ![image](https://user-images.githubusercontent.com/1778742/113238897-b5680e80-92ba-11eb-9ce6-7026abbf3bbb.png)
> 
> But yes, the redirect issue still happens for you as well.

Yup, and I noticed that a few other pods which were released yesterday have the same redirecting issue. I believe cocoapods devs will be working on it soon. I understand sometimes it takes time to make a proper fix. :)
