### ISSUE TITLE
DNS error for Search API

### ISSUE THREAD

**Issue by aleksandergrzyb** [CocoaPods/cocoapods.org#445]
👋, is [Search API](https://blog.cocoapods.org/Search-API-Version-1/) still maintained? 🤔 For me currently it results with DNS error.

**Comment by igor-makarov** [comment]
I think judging by the archived repo ([here](https://github.com/CocoaPods/search.cocoapods.org)), it's deprecated.

The new search is uses Algolia ([public API details here](https://github.com/CocoaPods/Specs/blob/master/AlgoliaSearch.yml))

**Comment by igor-makarov** [comment]
@floere @orta do you know anything about this hostname?
`cocoapods-search-elb-37181813.us-east-2.elb.amazonaws.com`

**Comment by orta** [comment]
looks like an elastic search URL from someone else, don't think that was ever from us

**Comment by igor-makarov** [comment]
I'm gonna close this now because search has been deprecated.

@aleksandergrzyb you can use the public API key and consult Algolia's documentation for more info.
