### ISSUE TITLE
Internal Server Error when navigating to pods page

### ISSUE THREAD

**Issue by maikelvdh** [CocoaPods/cocoapods.org#495]
When trying to navigate to for example https://cocoapods.org/pods/CoreGPX or https://cocoapods.org/pods/CoreNavigation or https://cocoapods.org/pods/CoreParser and many other pods you get as a result consistently internal server errors.

**Comment by amorde** [comment]
Thanks for reporting. I see the issue. This was introduced in https://github.com/CocoaPods/cocoapods.org/pull/494.

**Comment by amorde** [comment]
@maikelvdh this is now fixed
